nodeLinker: pnp
enableGlobalCache: false

packageExtensions:
  "@cucumber/cucumber@*":
    dependencies:
      ts-node: "*"
  "postcss-loader@*":
    dependencies:
      postcss-flexbugs-fixes: "*"
      postcss-normalize: "*"
      postcss-preset-env: "*"
      browserslist: "*"
