[project]
name = "userclouds"
version = "0.1.0"
description = "An open-source identity management platform that simplifies authentication, authorization, and user data handling for modern applications."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.40.35",
    "pyyaml>=6.0.2",
    "setuptools>=80.9.0",
]
