// NOTE: automatically generated file -- DO NOT EDIT

package tenantdb

func init() {
	UsedColumns["accessors"] = []string{
		"access_policy_id",
		"are_column_access_policies_overridden",
		"column_ids",
		"created",
		"data_life_cycle_state",
		"deleted",
		"description",
		"id",
		"is_audit_logged",
		"is_autogenerated",
		"is_system",
		"name",
		"purpose_ids",
		"search_column_id",
		"selector_config",
		"token_access_policy_ids",
		"transformer_ids",
		"updated",
		"use_search_index",
		"version",
	}
}
