// NOTE: automatically generated file -- DO NOT EDIT

package tenantdb

func init() {
	UsedColumns["access_policies"] = []string{
		"component_ids",
		"component_parameters",
		"component_types",
		"created",
		"deleted",
		"description",
		"id",
		"is_autogenerated",
		"is_system",
		"metadata",
		"name",
		"policy_type",
		"tag_ids",
		"thresholds",
		"updated",
		"version",
	}
}
