// NOTE: automatically generated file -- DO NOT EDIT

package tenantdb

import "userclouds.com/infra/migrate"

// these schemas are autogenerated to match all the applied migrations for test perf

// Schema defines the database schema for this package
var Schema = migrate.Schema{
	Migrations:       Migrations,
	CreateStatements: schemas,
	Columns:          UsedColumns,
	PostgresOnlyExtensions: []string{
		"btree_gin",
		"pg_trgm",
	},
}

var schemas = []string{
	`CREATE EXTENSION IF NOT EXISTS btree_gin WITH SCHEMA public;`,
	`COMMENT ON EXTENSION btree_gin IS 'support for indexing common datatypes in GIN';`,
	`CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA public;`,
	`COMMENT ON EXTENSION pg_trgm IS 'text similarity measurement and index searching based on trigrams';`,
	`CREATE TABLE public.access_policies (
    id uuid NOT NULL,
    created timestamp without time zone DEFAULT now() NOT NULL,
    updated timestamp without time zone NOT NULL,
    deleted timestamp without time zone DEFAULT '0001-01-01 00:00:00'::timestamp without time zone NOT NULL,
    version bigint NOT NULL,
    function character varying DEFAULT ''::character varying NOT NULL,
    parameters character varying DEFAULT ''::character varying,
    name character varying NOT NULL,
    description character varying NOT NULL,
    policy_type bigint NOT NULL,
    tag_ids uuid[],
    component_policy_ids uuid[],
    component_ids uuid[],
    component_parameters character varying[],
    component_types integer[],
    is_system boolean DEFAULT false NOT NULL,
    is_autogenerated boolean DEFAULT false NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    thresholds jsonb DEFAULT '{}'::jsonb NOT NULL
);`,
	`CREATE TABLE public.access_policy_templates (
    id uuid NOT NULL,
    created timestamp without time zone DEFAULT now() NOT NULL,
    updated timestamp without time zone NOT NULL,
    deleted timestamp without time zone DEFAULT '0001-01-01 00:00:00'::timestamp without time zone NOT NULL,
    name character varying DEFAULT ''::character varying NOT NULL,
    description character varying DEFAULT ''::character varying NOT NULL,
    function character varying NOT NULL,
    version bigint NOT NULL,
    is_system boolean DEFAULT false NOT NULL
);`,
	`CREATE TABLE public.accessor_search_indices (
    id uuid NOT NULL,
    deleted timestamp without time zone DEFAULT '0001-01-01 00:00:00'::timestamp without time zone NOT NULL,
    created timestamp without time zone DEFAULT now() NOT NULL,
    updated timestamp without time zone DEFAULT now() NOT NULL,
    user_search_index_id uuid NOT NULL,
    query_type character varying NOT NULL
);`,
	`CREATE TABLE public.accessors (
    id uuid NOT NULL,
    created timestamp without time zone DEFAULT now() NOT NULL,
    updated timestamp without time zone NOT NULL,
    deleted timestamp without time zone DEFAULT '0001-01-01 00:00:00'::timestamp without time zone NOT NULL,
    name character varying NOT NULL,
    description character varying NOT NULL,
    version bigint NOT NULL,
    access_policy_id uuid NOT NULL,
    selector_config jsonb DEFAULT '{}'::jsonb NOT NULL,
    column_ids uuid[] DEFAULT ARRAY[]::uuid[] NOT NULL,
    transformer_ids uuid[] DEFAULT ARRAY[]::uuid[] NOT NULL,
    token_access_policy_id uuid DEFAULT '00000000-0000-0000-0000-000000000000'::uuid NOT NULL,
    purpose_ids uuid[] DEFAULT ARRAY[]::uuid[] NOT NULL,
    is_system boolean DEFAULT false NOT NULL,
    data_life_cycle_state bigint DEFAULT 0 NOT NULL,
    is_audit_logged boolean DEFAULT false NOT NULL,
    is_autogenerated boolean DEFAULT false NOT NULL,
    are_column_access_policies_overridden boolean DEFAULT false NOT NULL,
    token_access_policy_ids uuid[] DEFAULT ARRAY[]::uuid[] NOT NULL,
    search_column_id uuid DEFAULT '00000000-0000-0000-0000-000000000000'::uuid NOT NULL,
    use_search_index boolean DEFAULT false NOT NULL
);`,
	`CREATE TABLE public.acme_certificates (
    id uuid NOT NULL,
    created timestamp without time zone DEFAULT now() NOT NULL,
    updated timestamp without time zone NOT NULL,
    deleted timestamp without time zone DEFAULT '0001-01-01 00:00:00'::timestamp without time zone NOT NULL,
    status character varying NOT NULL,
    order_id uuid NOT NULL,
    private_key character varying NOT NULL,
    certificate character varying NOT NULL,
    certificate_chain character varying NOT NULL,
    not_after timestamp without time zone DEFAULT '0001-01-01 00:00:00'::timestamp without time zone NOT NULL
);`,
	`CREATE TABLE public.acme_orders (
    id uuid NOT NULL,
    created timestamp without time zone DEFAULT now() NOT NULL,
    updated timestamp without time zone NOT NULL,
    deleted timestamp without time zone DEFAULT '0001-01-01 00:00:00'::timestamp without time zone NOT NULL,
    status character varying NOT NULL,
    url character varying NOT NULL,
    host character varying NOT NULL,
    token character varying NOT NULL,
    challenge_url character varying NOT NULL,
    tenant_url_id uuid NOT NULL
);`,
	`CREATE TABLE public.auditlog (
    id uuid NOT NULL,
    created timestamp without time zone DEFAULT now() NOT NULL,
    updated timestamp without time zone NOT NULL,
    deleted timestamp without time zone DEFAULT '0001-01-01 00:00:00'::timestamp without time zone NOT NULL,
    actor_id character varying NOT NULL,
    type character varying,
    payload jsonb NOT NULL
);`,
	`CREATE TABLE public.authns_password (
    id uuid NOT NULL,
    created timestamp without time zone DEFAULT now() NOT NULL,
    updated timestamp without time zone NOT NULL,
    user_id uuid NOT NULL,
    username character varying NOT NULL,
    password character varying NOT NULL,
    deleted timestamp without time zone DEFAULT '0001-01-01 00:00:00'::timestamp without time zone NOT NULL
);`,
	`CREATE TABLE public.authns_social (
    id uuid NOT NULL,
    created timestamp without time zone DEFAULT now() NOT NULL,
    updated timestamp without time zone NOT NULL,
    user_id uuid NOT NULL,
    type bigint NOT NULL,
    oidc_sub character varying NOT NULL,
    deleted timestamp without time zone DEFAULT '0001-01-01 00:00:00'::timestamp without time zone NOT NULL,
    oidc_issuer_url character varying DEFAULT ''::character varying NOT NULL
);`,
	`CREATE TABLE public.column_value_retention_durations (
    id uuid NOT NULL,
    created timestamp without time zone DEFAULT now() NOT NULL,
    updated timestamp without time zone NOT NULL,
    deleted timestamp without time zone DEFAULT '0001-01-01 00:00:00'::timestamp without time zone NOT NULL,
    _version bigint DEFAULT 0 NOT NULL,
    column_id uuid DEFAULT '00000000-0000-0000-0000-000000000000'::uuid NOT NULL,
    purpose_id uuid DEFAULT '00000000-0000-0000-0000-000000000000'::uuid NOT NULL,
    duration_type bigint NOT NULL,
    duration_unit bigint NOT NULL,
    duration bigint NOT NULL
);`,
	`CREATE TABLE public.columns (
    id uuid NOT NULL,
    created timestamp without time zone DEFAULT now() NOT NULL,
    updated timestamp without time zone NOT NULL,
    deleted timestamp without time zone DEFAULT '0001-01-01 00:00:00'::timestamp without time zone NOT NULL,
    name character varying NOT NULL,
    default_value character varying NOT NULL,
    attributes jsonb DEFAULT '{}'::jsonb NOT NULL,
    index_type bigint DEFAULT 0 NOT NULL,
    is_array boolean DEFAULT false NOT NULL,
    data_type_id uuid DEFAULT '00000000-0000-0000-0000-000000000000'::uuid NOT NULL,
    tbl character varying DEFAULT 'users'::character varying NOT NULL,
    sqlshim_database_id uuid DEFAULT '00000000-0000-0000-0000-000000000000'::uuid NOT NULL,
    default_transformer_id uuid DEFAULT 'c0b5b2a1-0b1f-4b9f-8b1a-1b1f4b9f8b1a'::uuid NOT NULL,
    default_token_access_policy_id uuid DEFAULT '00000000-0000-0000-0000-000000000000'::uuid NOT NULL,
    access_policy_id uuid DEFAULT '3f380e42-0b21-4570-a312-91e1b80386fa'::uuid NOT NULL,
    search_indexed boolean DEFAULT false NOT NULL
);`,
	`CREATE TABLE public.custom_pages (
    id uuid NOT NULL,
    created timestamp without time zone DEFAULT now() NOT NULL,
    updated timestamp without time zone NOT NULL,
    deleted timestamp without time zone DEFAULT '0001-01-01 00:00:00'::timestamp without time zone NOT NULL,
    app_id uuid NOT NULL,
    page_name character varying NOT NULL,
    page_source character varying NOT NULL
);`,
	`CREATE TABLE public.data_source_elements (
    id uuid NOT NULL,
    deleted timestamp without time zone DEFAULT '0001-01-01 00:00:00'::timestamp without time zone NOT NULL,
    created timestamp without time zone DEFAULT now() NOT NULL,
    updated timestamp without time zone DEFAULT now() NOT NULL,
    data_source_id uuid NOT NULL,
    path character varying NOT NULL,
    type character varying NOT NULL,
    metadata jsonb NOT NULL
);`,
	`CREATE TABLE public.data_sources (
    id uuid NOT NULL,
    deleted timestamp without time zone DEFAULT '0001-01-01 00:00:00'::timestamp without time zone NOT NULL,
    created timestamp without time zone DEFAULT now() NOT NULL,
    updated timestamp without time zone DEFAULT now() NOT NULL,
    type character varying NOT NULL,
    name character varying NOT NULL,
    config jsonb NOT NULL,
    metadata jsonb NOT NULL
);`,
	`CREATE TABLE public.data_types (
    id uuid NOT NULL,
    created timestamp without time zone DEFAULT now() NOT NULL,
    updated timestamp without time zone NOT NULL,
    deleted timestamp without time zone DEFAULT '0001-01-01 00:00:00'::timestamp without time zone NOT NULL,
    name character varying NOT NULL,
    description character varying NOT NULL,
    concrete_data_type_id uuid NOT NULL,
    composite_attributes jsonb DEFAULT '{}'::jsonb NOT NULL
);`,
	`CREATE TABLE public.delegation_invites (
    id uuid NOT NULL,
    created timestamp without time zone DEFAULT now() NOT NULL,
    updated timestamp without time zone NOT NULL,
    deleted timestamp without time zone DEFAULT '0001-01-01 00:00:00'::timestamp without time zone NOT NULL,
    client_id character varying NOT NULL,
    invited_to_account_id character varying NOT NULL
);`,
	`CREATE TABLE public.delegation_states (
    id uuid NOT NULL,
    created timestamp without time zone DEFAULT now() NOT NULL,
    updated timestamp without time zone NOT NULL,
    deleted timestamp without time zone DEFAULT '0001-01-01 00:00:00'::timestamp without time zone NOT NULL,
    authenticated_user_id character varying NOT NULL
);`,
	`CREATE TABLE public.edge_types (
    id uuid NOT NULL,
    created timestamp without time zone DEFAULT now() NOT NULL,
    updated timestamp without time zone NOT NULL,
    type_name character varying NOT NULL,
    source_object_type_id uuid NOT NULL,
    target_object_type_id uuid NOT NULL,
    deleted timestamp without time zone DEFAULT '0001-01-01 00:00:00'::timestamp without time zone NOT NULL,
    attributes jsonb DEFAULT '[]'::jsonb NOT NULL,
    organization_id uuid DEFAULT '00000000-0000-0000-0000-000000000000'::uuid NOT NULL
);`,
	`CREATE TABLE public.edges (
    id uuid NOT NULL,
    created timestamp without time zone DEFAULT now() NOT NULL,
    updated timestamp without time zone NOT NULL,
    edge_type_id uuid NOT NULL,
    source_object_id uuid NOT NULL,
    target_object_id uuid NOT NULL,
    deleted timestamp without time zone DEFAULT '0001-01-01 00:00:00'::timestamp without time zone NOT NULL
);`,
	`CREATE TABLE public.idp_data_import_jobs (
    id uuid NOT NULL,
    created timestamp without time zone DEFAULT now() NOT NULL,
    updated timestamp without time zone NOT NULL,
    deleted timestamp without time zone DEFAULT '0001-01-01 00:00:00'::timestamp without time zone NOT NULL,
    last_run_time timestamp without time zone NOT NULL,
    import_type character varying NOT NULL,
    status character varying NOT NULL,
    error character varying NOT NULL,
    s3_bucket character varying NOT NULL,
    object_key character varying NOT NULL,
    expiration_minutes bigint NOT NULL,
    file_size bigint NOT NULL,
    processed_size bigint NOT NULL,
    processed_record_count bigint NOT NULL,
    failed_record_count bigint NOT NULL,
    failed_records jsonb NOT NULL
);`,
	`CREATE TABLE public.idp_sync_records (
    id uuid NOT NULL,
    created timestamp without time zone DEFAULT now() NOT NULL,
    updated timestamp without time zone NOT NULL,
    deleted timestamp without time zone DEFAULT '0001-01-01 00:00:00'::timestamp without time zone NOT NULL,
    sync_run_id uuid NOT NULL,
    user_id character varying NOT NULL,
    error character varying NOT NULL,
    object_id character varying DEFAULT ''::character varying NOT NULL,
    warning character varying DEFAULT ''::character varying NOT NULL
);`,
	`CREATE TABLE public.idp_sync_runs (
    id uuid NOT NULL,
    created timestamp without time zone DEFAULT now() NOT NULL,
    updated timestamp without time zone NOT NULL,
    deleted timestamp without time zone DEFAULT '0001-01-01 00:00:00'::timestamp without time zone NOT NULL,
    active_provider_id uuid NOT NULL,
    follower_provider_ids uuid[] DEFAULT ARRAY[]::uuid[] NOT NULL,
    since timestamp without time zone NOT NULL,
    until timestamp without time zone NOT NULL,
    error character varying NOT NULL,
    total_records bigint DEFAULT 0 NOT NULL,
    failed_records bigint DEFAULT 0 NOT NULL,
    type character varying DEFAULT ''::character varying NOT NULL,
    warning_records bigint DEFAULT 0 NOT NULL
);`,
	`CREATE TABLE public.mfa_requests (
    id uuid NOT NULL,
    created timestamp without time zone DEFAULT now() NOT NULL,
    updated timestamp without time zone NOT NULL,
    user_id uuid NOT NULL,
    issued timestamp without time zone NOT NULL,
    code character varying NOT NULL,
    deleted timestamp without time zone DEFAULT '0001-01-01 00:00:00'::timestamp without time zone NOT NULL,
    channel_id uuid DEFAULT '00000000-0000-0000-0000-000000000000'::uuid NOT NULL,
    supported_channel_types jsonb DEFAULT '{}'::jsonb NOT NULL
);`,
	`CREATE TABLE public.mfa_states (
    id uuid NOT NULL,
    created timestamp without time zone DEFAULT now() NOT NULL,
    updated timestamp without time zone NOT NULL,
    deleted timestamp without time zone DEFAULT '0001-01-01 00:00:00'::timestamp without time zone NOT NULL,
    session_id uuid NOT NULL,
    token character varying NOT NULL,
    provider uuid NOT NULL,
    supported_channels jsonb DEFAULT '{}'::jsonb NOT NULL,
    channel_id uuid DEFAULT '00000000-0000-0000-0000-000000000000'::uuid NOT NULL,
    purpose bigint DEFAULT 0 NOT NULL,
    challenge_state bigint DEFAULT 0 NOT NULL,
    evaluate_supported_channels boolean DEFAULT false NOT NULL
);`,
	`CREATE TABLE public.migrations (
    tbl character varying(1000) NOT NULL,
    version integer NOT NULL,
    dsc character varying(1000),
    up character varying(10000) NOT NULL,
    down character varying(1000)
);`,
	`CREATE TABLE public.mutators (
    id uuid NOT NULL,
    created timestamp without time zone DEFAULT now() NOT NULL,
    updated timestamp without time zone NOT NULL,
    deleted timestamp without time zone DEFAULT '0001-01-01 00:00:00'::timestamp without time zone NOT NULL,
    name character varying NOT NULL,
    description character varying NOT NULL,
    version bigint NOT NULL,
    access_policy_id uuid NOT NULL,
    selector_config jsonb DEFAULT '{}'::jsonb NOT NULL,
    column_ids uuid[] DEFAULT ARRAY[]::uuid[] NOT NULL,
    validator_ids uuid[] DEFAULT ARRAY[]::uuid[] NOT NULL,
    is_system boolean DEFAULT false NOT NULL
);`,
	`CREATE TABLE public.object_types (
    id uuid NOT NULL,
    created timestamp without time zone DEFAULT now() NOT NULL,
    updated timestamp without time zone NOT NULL,
    type_name character varying NOT NULL,
    deleted timestamp without time zone DEFAULT '0001-01-01 00:00:00'::timestamp without time zone NOT NULL
);`,
	`CREATE TABLE public.objects (
    id uuid NOT NULL,
    created timestamp without time zone DEFAULT now() NOT NULL,
    updated timestamp without time zone NOT NULL,
    alias character varying,
    type_id uuid NOT NULL,
    deleted timestamp without time zone DEFAULT '0001-01-01 00:00:00'::timestamp without time zone NOT NULL,
    organization_id uuid DEFAULT '00000000-0000-0000-0000-000000000000'::uuid NOT NULL
);`,
	`CREATE TABLE public.oidc_login_sessions (
    id uuid NOT NULL,
    created timestamp without time zone DEFAULT now() NOT NULL,
    updated timestamp without time zone NOT NULL,
    deleted timestamp without time zone DEFAULT '0001-01-01 00:00:00'::timestamp without time zone NOT NULL,
    client_id character varying NOT NULL,
    response_types character varying NOT NULL,
    redirect_uri character varying NOT NULL,
    state character varying NOT NULL,
    scopes character varying NOT NULL,
    nonce character varying NOT NULL,
    social_provider bigint NOT NULL,
    mfa_state_id uuid NOT NULL,
    otp_state_id uuid NOT NULL,
    pkce_state_id uuid NOT NULL,
    delegation_state_id uuid DEFAULT '00000000-0000-0000-0000-000000000000'::uuid NOT NULL,
    add_authn_provider_data jsonb DEFAULT '{}'::jsonb NOT NULL,
    plex_token_id uuid DEFAULT '00000000-0000-0000-0000-000000000000'::uuid NOT NULL,
    mfa_channel_states jsonb DEFAULT '{}'::jsonb NOT NULL,
    oidc_issuer_url character varying DEFAULT ''::character varying NOT NULL
);`,
	`CREATE TABLE public.organizations (
    id uuid NOT NULL,
    created timestamp without time zone DEFAULT now() NOT NULL,
    updated timestamp without time zone NOT NULL,
    deleted timestamp without time zone DEFAULT '0001-01-01 00:00:00'::timestamp without time zone NOT NULL,
    name character varying NOT NULL,
    region character varying DEFAULT ''::character varying NOT NULL
);`,
	`CREATE TABLE public.otp_states (
    id uuid NOT NULL,
    created timestamp without time zone DEFAULT now() NOT NULL,
    updated timestamp without time zone NOT NULL,
    deleted timestamp without time zone DEFAULT '0001-01-01 00:00:00'::timestamp without time zone NOT NULL,
    session_id uuid NOT NULL,
    email character varying NOT NULL,
    code character varying NOT NULL,
    expires timestamp without time zone NOT NULL,
    used boolean NOT NULL,
    purpose bigint NOT NULL,
    user_id character varying DEFAULT ''::character varying NOT NULL
);`,
	`CREATE TABLE public.pkce_states (
    id uuid NOT NULL,
    created timestamp without time zone DEFAULT now() NOT NULL,
    updated timestamp without time zone NOT NULL,
    deleted timestamp without time zone DEFAULT '0001-01-01 00:00:00'::timestamp without time zone NOT NULL,
    session_id uuid NOT NULL,
    code_challenge character varying NOT NULL,
    method bigint NOT NULL,
    used boolean NOT NULL
);`,
	`CREATE TABLE public.plex_config (
    id uuid NOT NULL,
    created timestamp without time zone DEFAULT now() NOT NULL,
    updated timestamp without time zone NOT NULL,
    plex_config jsonb NOT NULL,
    deleted timestamp without time zone DEFAULT '0001-01-01 00:00:00'::timestamp without time zone NOT NULL,
    _version bigint DEFAULT 0 NOT NULL
);`,
	`CREATE TABLE public.plex_tokens (
    id uuid NOT NULL,
    created timestamp without time zone DEFAULT now() NOT NULL,
    updated timestamp without time zone NOT NULL,
    deleted timestamp without time zone DEFAULT '0001-01-01 00:00:00'::timestamp without time zone NOT NULL,
    client_id character varying NOT NULL,
    auth_code character varying NOT NULL,
    access_token character varying NOT NULL,
    id_token character varying NOT NULL,
    idp_subject character varying NOT NULL,
    scopes character varying NOT NULL,
    session_id uuid NOT NULL,
    underlying_token character varying DEFAULT ''::character varying NOT NULL,
    refresh_token character varying DEFAULT ''::character varying NOT NULL
);`,
	`CREATE TABLE public.policy_secrets (
    id uuid NOT NULL,
    deleted timestamp without time zone DEFAULT '0001-01-01 00:00:00'::timestamp without time zone NOT NULL,
    created timestamp without time zone DEFAULT now() NOT NULL,
    updated timestamp without time zone DEFAULT now() NOT NULL,
    name character varying NOT NULL,
    value character varying NOT NULL
);`,
	`CREATE TABLE public.purposes (
    id uuid NOT NULL,
    created timestamp without time zone DEFAULT now() NOT NULL,
    updated timestamp without time zone NOT NULL,
    deleted timestamp without time zone DEFAULT '0001-01-01 00:00:00'::timestamp without time zone NOT NULL,
    name character varying NOT NULL,
    description character varying NOT NULL,
    is_system boolean DEFAULT false NOT NULL
);`,
	`CREATE TABLE public.saml_sessions (
    id uuid NOT NULL,
    created timestamp without time zone DEFAULT now() NOT NULL,
    updated timestamp without time zone NOT NULL,
    deleted timestamp without time zone DEFAULT '0001-01-01 00:00:00'::timestamp without time zone NOT NULL,
    expire_time timestamp without time zone NOT NULL,
    _index character varying NOT NULL,
    name_id character varying NOT NULL,
    name_id_format character varying NOT NULL,
    subject_id character varying NOT NULL,
    groups jsonb DEFAULT '[]'::jsonb NOT NULL,
    user_name character varying NOT NULL,
    user_email character varying NOT NULL,
    user_common_name character varying NOT NULL,
    user_surname character varying NOT NULL,
    user_given_name character varying NOT NULL,
    user_scoped_affiliation character varying NOT NULL,
    custom_attributes jsonb DEFAULT '[]'::jsonb NOT NULL,
    state character varying NOT NULL,
    relay_state character varying NOT NULL,
    request_buffer bytea NOT NULL
);`,
	`CREATE TABLE public.shim_object_stores (
    id uuid NOT NULL,
    deleted timestamp without time zone DEFAULT '0001-01-01 00:00:00'::timestamp without time zone NOT NULL,
    created timestamp without time zone DEFAULT now() NOT NULL,
    updated timestamp without time zone DEFAULT now() NOT NULL,
    name character varying NOT NULL,
    type character varying NOT NULL,
    region character varying NOT NULL,
    access_key_id character varying NOT NULL,
    secret_access_key character varying NOT NULL,
    access_policy_id uuid NOT NULL,
    role_arn character varying DEFAULT ''::character varying NOT NULL
);`,
	`CREATE TABLE public.sqlshim_databases (
    id uuid NOT NULL,
    deleted timestamp without time zone DEFAULT '0001-01-01 00:00:00'::timestamp without time zone NOT NULL,
    created timestamp without time zone DEFAULT now() NOT NULL,
    updated timestamp without time zone DEFAULT now() NOT NULL,
    name character varying NOT NULL,
    type character varying NOT NULL,
    host character varying NOT NULL,
    port bigint NOT NULL,
    username character varying NOT NULL,
    password character varying NOT NULL,
    schemas_updated timestamp without time zone DEFAULT '0001-01-01 00:00:00'::timestamp without time zone NOT NULL,
    schemas_update_scheduled timestamp without time zone DEFAULT '0001-01-01 00:00:00'::timestamp without time zone NOT NULL,
    schemas character varying[] DEFAULT ARRAY[]::character varying[] NOT NULL
);`,
	`CREATE TABLE public.token_records (
    id uuid NOT NULL,
    created timestamp without time zone DEFAULT now() NOT NULL,
    updated timestamp without time zone NOT NULL,
    deleted timestamp without time zone DEFAULT '0001-01-01 00:00:00'::timestamp without time zone NOT NULL,
    transformer_id uuid NOT NULL,
    access_policy_id uuid NOT NULL,
    token character varying NOT NULL,
    data character varying NOT NULL,
    user_id uuid DEFAULT '00000000-0000-0000-0000-000000000000'::uuid NOT NULL,
    column_id uuid DEFAULT '00000000-0000-0000-0000-000000000000'::uuid NOT NULL,
    transformer_version integer DEFAULT 0 NOT NULL
);`,
	`CREATE TABLE public.transformers (
    id uuid NOT NULL,
    created timestamp without time zone DEFAULT now() NOT NULL,
    updated timestamp without time zone NOT NULL,
    deleted timestamp without time zone DEFAULT '0001-01-01 00:00:00'::timestamp without time zone NOT NULL,
    name character varying NOT NULL,
    description character varying NOT NULL,
    transform_type bigint NOT NULL,
    function character varying NOT NULL,
    parameters character varying NOT NULL,
    tag_ids uuid[],
    is_system boolean DEFAULT false NOT NULL,
    reuse_existing_token boolean DEFAULT true,
    input_data_type_id uuid DEFAULT '00000000-0000-0000-0000-000000000000'::uuid NOT NULL,
    output_data_type_id uuid DEFAULT '00000000-0000-0000-0000-000000000000'::uuid NOT NULL,
    version integer DEFAULT 0 NOT NULL
);`,
	`CREATE TABLE public.user_cleanup_candidates (
    id uuid NOT NULL,
    deleted timestamp without time zone DEFAULT '0001-01-01 00:00:00'::timestamp without time zone NOT NULL,
    created timestamp without time zone DEFAULT now() NOT NULL,
    updated timestamp without time zone DEFAULT now() NOT NULL,
    user_id uuid NOT NULL,
    cleanup_reason bigint NOT NULL
);`,
	`CREATE TABLE public.user_column_post_delete_values (
    id uuid NOT NULL,
    created timestamp without time zone DEFAULT now() NOT NULL,
    updated timestamp without time zone NOT NULL,
    deleted timestamp without time zone DEFAULT '0001-01-01 00:00:00'::timestamp without time zone NOT NULL,
    _version bigint NOT NULL,
    column_id uuid NOT NULL,
    user_id uuid NOT NULL,
    varchar_value character varying,
    boolean_value boolean,
    int_value bigint,
    timestamp_value timestamp without time zone,
    uuid_value uuid,
    jsonb_value jsonb,
    ordering bigint NOT NULL,
    consented_purpose_ids uuid[] NOT NULL,
    retention_timeouts character varying[] NOT NULL,
    value_type bigint DEFAULT 0 NOT NULL
);`,
	`CREATE TABLE public.user_column_pre_delete_values (
    id uuid NOT NULL,
    created timestamp without time zone DEFAULT now() NOT NULL,
    updated timestamp without time zone NOT NULL,
    deleted timestamp without time zone DEFAULT '0001-01-01 00:00:00'::timestamp without time zone NOT NULL,
    _version bigint NOT NULL,
    column_id uuid NOT NULL,
    user_id uuid NOT NULL,
    varchar_value character varying,
    varchar_unique_value character varying,
    boolean_value boolean,
    int_value bigint,
    int_unique_value bigint,
    timestamp_value timestamp without time zone,
    uuid_value uuid,
    uuid_unique_value uuid,
    jsonb_value jsonb,
    ordering bigint NOT NULL,
    consented_purpose_ids uuid[] NOT NULL,
    retention_timeouts character varying[] NOT NULL,
    value_type bigint DEFAULT 0 NOT NULL
);`,
	`CREATE TABLE public.user_mfa_configuration (
    id uuid NOT NULL,
    created timestamp without time zone DEFAULT now() NOT NULL,
    updated timestamp without time zone NOT NULL,
    deleted timestamp without time zone DEFAULT '0001-01-01 00:00:00'::timestamp without time zone NOT NULL,
    last_evaluated timestamp without time zone DEFAULT '0001-01-01 00:00:00'::timestamp without time zone NOT NULL,
    mfa_channels jsonb DEFAULT '{}'::jsonb NOT NULL
);`,
	`CREATE TABLE public.user_search_indices (
    id uuid NOT NULL,
    deleted timestamp without time zone DEFAULT '0001-01-01 00:00:00'::timestamp without time zone NOT NULL,
    created timestamp without time zone DEFAULT now() NOT NULL,
    updated timestamp without time zone DEFAULT now() NOT NULL,
    name character varying NOT NULL,
    description character varying,
    data_life_cycle_state integer NOT NULL,
    type character varying NOT NULL,
    settings jsonb DEFAULT '{}'::jsonb NOT NULL,
    column_ids uuid[],
    change_feed_job_id bigint DEFAULT 0 NOT NULL,
    bootstrapped timestamp without time zone DEFAULT '0001-01-01 00:00:00'::timestamp without time zone NOT NULL,
    enabled timestamp without time zone DEFAULT '0001-01-01 00:00:00'::timestamp without time zone NOT NULL,
    searchable timestamp without time zone DEFAULT '0001-01-01 00:00:00'::timestamp without time zone NOT NULL,
    last_bootstrapped_value_id uuid DEFAULT '00000000-0000-0000-0000-000000000000'::uuid NOT NULL,
    last_regional_bootstrapped_value_ids jsonb DEFAULT '{}'::jsonb NOT NULL
);`,
	`CREATE TABLE public.users (
    id uuid NOT NULL,
    created timestamp without time zone DEFAULT now() NOT NULL,
    updated timestamp without time zone NOT NULL,
    deleted timestamp without time zone DEFAULT '0001-01-01 00:00:00'::timestamp without time zone NOT NULL,
    organization_id uuid DEFAULT '00000000-0000-0000-0000-000000000000'::uuid NOT NULL,
    _version bigint DEFAULT 0 NOT NULL,
    region character varying DEFAULT ''::character varying NOT NULL
);`,
	`ALTER TABLE ONLY public.access_policies
    ADD CONSTRAINT access_policies_name_version_deleted_key UNIQUE (name, version, deleted);`,
	`ALTER TABLE ONLY public.access_policies
    ADD CONSTRAINT access_policies_pkey PRIMARY KEY (deleted, id, version);`,
	`ALTER TABLE ONLY public.access_policy_templates
    ADD CONSTRAINT access_policy_templates_deleted_name_version_key UNIQUE (deleted, name, version);`,
	`ALTER TABLE ONLY public.access_policy_templates
    ADD CONSTRAINT access_policy_templates_pkey PRIMARY KEY (deleted, id, version);`,
	`ALTER TABLE ONLY public.accessor_search_indices
    ADD CONSTRAINT accessor_search_indices_pkey PRIMARY KEY (deleted, id);`,
	`ALTER TABLE ONLY public.accessors
    ADD CONSTRAINT accessors_name_version_deleted_key UNIQUE (name, version, deleted);`,
	`ALTER TABLE ONLY public.accessors
    ADD CONSTRAINT accessors_pkey PRIMARY KEY (deleted, id, version);`,
	`ALTER TABLE ONLY public.acme_certificates
    ADD CONSTRAINT acme_certificates_pkey PRIMARY KEY (deleted, id);`,
	`ALTER TABLE ONLY public.acme_orders
    ADD CONSTRAINT acme_orders_pkey PRIMARY KEY (deleted, id);`,
	`ALTER TABLE ONLY public.auditlog
    ADD CONSTRAINT auditlog_pkey PRIMARY KEY (deleted, id);`,
	`ALTER TABLE ONLY public.authns_password
    ADD CONSTRAINT authns_password_pkey PRIMARY KEY (deleted, id);`,
	`ALTER TABLE ONLY public.authns_password
    ADD CONSTRAINT authns_password_username_deleted_key UNIQUE (username, deleted);`,
	`ALTER TABLE ONLY public.authns_social
    ADD CONSTRAINT authns_social_pkey PRIMARY KEY (deleted, id);`,
	`ALTER TABLE ONLY public.authns_social
    ADD CONSTRAINT authns_social_type_oidc_issuer_url_oidc_sub_deleted_key UNIQUE (type, oidc_issuer_url, oidc_sub, deleted);`,
	`ALTER TABLE ONLY public.column_value_retention_durations
    ADD CONSTRAINT column_value_retention_durati_deleted_duration_type_purpose_key UNIQUE (deleted, duration_type, purpose_id, column_id);`,
	`ALTER TABLE ONLY public.column_value_retention_durations
    ADD CONSTRAINT column_value_retention_durations_pkey PRIMARY KEY (deleted, id);`,
	`ALTER TABLE ONLY public.columns
    ADD CONSTRAINT columns_deleted_sqlshim_database_id_tbl_name_key UNIQUE (deleted, sqlshim_database_id, tbl, name);`,
	`ALTER TABLE ONLY public.columns
    ADD CONSTRAINT columns_pkey PRIMARY KEY (deleted, id);`,
	`ALTER TABLE ONLY public.custom_pages
    ADD CONSTRAINT custom_pages_pkey PRIMARY KEY (deleted, id);`,
	`ALTER TABLE ONLY public.data_source_elements
    ADD CONSTRAINT data_source_elements_pkey PRIMARY KEY (deleted, id);`,
	`ALTER TABLE ONLY public.data_sources
    ADD CONSTRAINT data_sources_pkey PRIMARY KEY (deleted, id);`,
	`ALTER TABLE ONLY public.data_types
    ADD CONSTRAINT data_types_deleted_name_key UNIQUE (deleted, name);`,
	`ALTER TABLE ONLY public.data_types
    ADD CONSTRAINT data_types_pk PRIMARY KEY (deleted, id);`,
	`ALTER TABLE ONLY public.delegation_invites
    ADD CONSTRAINT delegation_invites_pkey PRIMARY KEY (deleted, id);`,
	`ALTER TABLE ONLY public.delegation_states
    ADD CONSTRAINT delegation_states_pkey PRIMARY KEY (deleted, id);`,
	`ALTER TABLE ONLY public.edge_types
    ADD CONSTRAINT edge_types_pkey PRIMARY KEY (deleted, id);`,
	`ALTER TABLE ONLY public.edge_types
    ADD CONSTRAINT edge_types_type_name_deleted_key UNIQUE (type_name, deleted);`,
	`ALTER TABLE ONLY public.edges
    ADD CONSTRAINT edges_pkey PRIMARY KEY (deleted, id);`,
	`ALTER TABLE ONLY public.edges
    ADD CONSTRAINT edges_source_object_id_target_object_id_edge_type_id_delete_key UNIQUE (source_object_id, target_object_id, edge_type_id, deleted);`,
	`ALTER TABLE ONLY public.idp_data_import_jobs
    ADD CONSTRAINT idp_data_import_jobs_pkey PRIMARY KEY (deleted, id);`,
	`ALTER TABLE ONLY public.idp_sync_records
    ADD CONSTRAINT idp_sync_records_pkey PRIMARY KEY (deleted, id);`,
	`ALTER TABLE ONLY public.idp_sync_runs
    ADD CONSTRAINT idp_sync_runs_pkey PRIMARY KEY (deleted, id);`,
	`ALTER TABLE ONLY public.mfa_requests
    ADD CONSTRAINT mfa_requests_pkey PRIMARY KEY (deleted, id);`,
	`ALTER TABLE ONLY public.mfa_states
    ADD CONSTRAINT mfa_states_pkey PRIMARY KEY (deleted, id);`,
	`ALTER TABLE ONLY public.migrations
    ADD CONSTRAINT migrations_pkey PRIMARY KEY (version);`,
	`ALTER TABLE ONLY public.mutators
    ADD CONSTRAINT mutators_name_version_deleted_key UNIQUE (name, version, deleted);`,
	`ALTER TABLE ONLY public.mutators
    ADD CONSTRAINT mutators_pkey PRIMARY KEY (deleted, id, version);`,
	`ALTER TABLE ONLY public.object_types
    ADD CONSTRAINT object_types_pkey PRIMARY KEY (deleted, id);`,
	`ALTER TABLE ONLY public.object_types
    ADD CONSTRAINT object_types_type_name_deleted_key UNIQUE (type_name, deleted);`,
	`ALTER TABLE ONLY public.objects
    ADD CONSTRAINT objects_alias_type_id_organization_id_deleted_key UNIQUE (alias, type_id, organization_id, deleted);`,
	`ALTER TABLE ONLY public.objects
    ADD CONSTRAINT objects_pkey PRIMARY KEY (deleted, id);`,
	`ALTER TABLE ONLY public.oidc_login_sessions
    ADD CONSTRAINT oidc_login_sessions_pkey PRIMARY KEY (deleted, id);`,
	`ALTER TABLE ONLY public.organizations
    ADD CONSTRAINT organizations_deleted_name_key UNIQUE (deleted, name);`,
	`ALTER TABLE ONLY public.organizations
    ADD CONSTRAINT organizations_pkey PRIMARY KEY (deleted, id);`,
	`ALTER TABLE ONLY public.otp_states
    ADD CONSTRAINT otp_states_pkey PRIMARY KEY (deleted, id);`,
	`ALTER TABLE ONLY public.pkce_states
    ADD CONSTRAINT pkce_states_pkey PRIMARY KEY (deleted, id);`,
	`ALTER TABLE ONLY public.plex_config
    ADD CONSTRAINT plex_config_pkey PRIMARY KEY (deleted, id);`,
	`ALTER TABLE ONLY public.plex_tokens
    ADD CONSTRAINT plex_tokens_access_token_key UNIQUE (access_token);`,
	`ALTER TABLE ONLY public.plex_tokens
    ADD CONSTRAINT plex_tokens_auth_code_key UNIQUE (auth_code);`,
	`ALTER TABLE ONLY public.plex_tokens
    ADD CONSTRAINT plex_tokens_pkey PRIMARY KEY (deleted, id);`,
	`ALTER TABLE ONLY public.policy_secrets
    ADD CONSTRAINT policy_secrets_deleted_name_key UNIQUE (deleted, name);`,
	`ALTER TABLE ONLY public.policy_secrets
    ADD CONSTRAINT policy_secrets_pkey PRIMARY KEY (deleted, id);`,
	`ALTER TABLE ONLY public.purposes
    ADD CONSTRAINT purposes_deleted_name_key UNIQUE (deleted, name);`,
	`ALTER TABLE ONLY public.purposes
    ADD CONSTRAINT purposes_pkey PRIMARY KEY (deleted, id);`,
	`ALTER TABLE ONLY public.saml_sessions
    ADD CONSTRAINT saml_sessions_pkey PRIMARY KEY (deleted, id);`,
	`ALTER TABLE ONLY public.shim_object_stores
    ADD CONSTRAINT shim_object_stores_pkey PRIMARY KEY (deleted, id);`,
	`ALTER TABLE ONLY public.sqlshim_databases
    ADD CONSTRAINT sqlshim_databases_pkey PRIMARY KEY (deleted, id);`,
	`ALTER TABLE ONLY public.token_records
    ADD CONSTRAINT token_records_id_deleted_key UNIQUE (id, deleted);`,
	`ALTER TABLE ONLY public.token_records
    ADD CONSTRAINT token_records_pkey PRIMARY KEY (deleted, token);`,
	`ALTER TABLE ONLY public.token_records
    ADD CONSTRAINT token_records_token_deleted_key UNIQUE (token, deleted);`,
	`ALTER TABLE ONLY public.transformers
    ADD CONSTRAINT transformers_name_version_deleted_key UNIQUE (name, version, deleted);`,
	`ALTER TABLE ONLY public.transformers
    ADD CONSTRAINT transformers_pkey PRIMARY KEY (deleted, id, version);`,
	`ALTER TABLE ONLY public.user_cleanup_candidates
    ADD CONSTRAINT user_cleanup_candidates_pkey PRIMARY KEY (deleted, id);`,
	`ALTER TABLE ONLY public.user_column_post_delete_values
    ADD CONSTRAINT user_column_post_delete_values_pk PRIMARY KEY (id);`,
	`ALTER TABLE ONLY public.user_column_pre_delete_values
    ADD CONSTRAINT user_column_pre_delete_values_column_id_int_unique_value_key UNIQUE (column_id, int_unique_value);`,
	`ALTER TABLE ONLY public.user_column_pre_delete_values
    ADD CONSTRAINT user_column_pre_delete_values_column_id_uuid_unique_value_key UNIQUE (column_id, uuid_unique_value);`,
	`ALTER TABLE ONLY public.user_column_pre_delete_values
    ADD CONSTRAINT user_column_pre_delete_values_column_id_varchar_unique_valu_key UNIQUE (column_id, varchar_unique_value);`,
	`ALTER TABLE ONLY public.user_column_pre_delete_values
    ADD CONSTRAINT user_column_pre_delete_values_pk PRIMARY KEY (id);`,
	`ALTER TABLE ONLY public.user_mfa_configuration
    ADD CONSTRAINT user_mfa_configuration_pkey PRIMARY KEY (deleted, id);`,
	`ALTER TABLE ONLY public.user_search_indices
    ADD CONSTRAINT user_search_indices_deleted_name_key UNIQUE (deleted, name);`,
	`ALTER TABLE ONLY public.user_search_indices
    ADD CONSTRAINT user_search_indices_pkey PRIMARY KEY (deleted, id);`,
	`ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (deleted, id);`,
	`CREATE INDEX authns_password_user_id_idx ON public.authns_password USING btree (user_id);`,
	`CREATE INDEX authns_social_user_id_idx ON public.authns_social USING btree (user_id);`,
	`CREATE INDEX edges_target_object_id_idx ON public.edges USING btree (target_object_id);`,
	`CREATE INDEX edges_updated_time ON public.edges USING btree (updated) INCLUDE (created, edge_type_id, source_object_id, target_object_id);`,
	`CREATE INDEX idp_sync_runs_active_provider_id_deleted_idx ON public.idp_sync_runs USING btree (active_provider_id, deleted);`,
	`CREATE INDEX user_column_post_delete_values_boolean ON public.user_column_post_delete_values USING btree (column_id, user_id, boolean_value);`,
	`CREATE INDEX user_column_post_delete_values_int ON public.user_column_post_delete_values USING btree (column_id, user_id, int_value);`,
	`CREATE INDEX user_column_post_delete_values_jsonb ON public.user_column_post_delete_values USING gin (column_id, user_id, jsonb_value);`,
	`CREATE INDEX user_column_post_delete_values_timestamp ON public.user_column_post_delete_values USING btree (column_id, user_id, timestamp_value);`,
	`CREATE INDEX user_column_post_delete_values_user_id_idx ON public.user_column_post_delete_values USING btree (user_id);`,
	`CREATE INDEX user_column_post_delete_values_uuid ON public.user_column_post_delete_values USING btree (column_id, user_id, uuid_value);`,
	`CREATE INDEX user_column_post_delete_values_varchar ON public.user_column_post_delete_values USING btree (column_id, user_id, varchar_value);`,
	`CREATE INDEX user_column_pre_delete_values_column_unique_varchar ON public.user_column_pre_delete_values USING btree (column_id, varchar_unique_value);`,
	`CREATE INDEX user_column_pre_delete_values_column_user_boolean ON public.user_column_pre_delete_values USING btree (column_id, user_id, boolean_value);`,
	`CREATE INDEX user_column_pre_delete_values_column_user_int ON public.user_column_pre_delete_values USING btree (column_id, user_id, int_value);`,
	`CREATE INDEX user_column_pre_delete_values_column_user_jsonb ON public.user_column_pre_delete_values USING gin (column_id, user_id, jsonb_value);`,
	`CREATE INDEX user_column_pre_delete_values_column_user_timestamp ON public.user_column_pre_delete_values USING btree (column_id, user_id, timestamp_value);`,
	`CREATE INDEX user_column_pre_delete_values_column_user_unique_int ON public.user_column_pre_delete_values USING btree (column_id, user_id, int_unique_value);`,
	`CREATE INDEX user_column_pre_delete_values_column_user_unique_uuid ON public.user_column_pre_delete_values USING btree (column_id, user_id, uuid_unique_value);`,
	`CREATE INDEX user_column_pre_delete_values_column_user_unique_varchar ON public.user_column_pre_delete_values USING btree (column_id, user_id, varchar_unique_value);`,
	`CREATE INDEX user_column_pre_delete_values_column_user_uuid ON public.user_column_pre_delete_values USING btree (column_id, user_id, uuid_value);`,
	`CREATE INDEX user_column_pre_delete_values_column_user_varchar ON public.user_column_pre_delete_values USING btree (column_id, user_id, varchar_value);`,
	`CREATE INDEX user_column_pre_delete_values_column_varchar ON public.user_column_pre_delete_values USING btree (column_id, varchar_value);`,
	`CREATE INDEX user_column_pre_delete_values_column_varchar_trgm ON public.user_column_pre_delete_values USING gin (column_id, varchar_value public.gin_trgm_ops);`,
	`CREATE INDEX user_column_pre_delete_values_column_varchar_unique_trgm ON public.user_column_pre_delete_values USING gin (column_id, varchar_unique_value public.gin_trgm_ops);`,
	`CREATE INDEX user_column_pre_delete_values_user_id_idx ON public.user_column_pre_delete_values USING btree (user_id);`,
}
