// auto-generated by genevents
// your changes will be preserved inside both the EventCodes constant block
// and the EventMap block, but names are auto-generated and so won't necessarily
// be used if they are incorrect
package events

import (
	"userclouds.com/infra/namespace/service"
	"userclouds.com/infra/uclog"
)

func init() {
	for k, ev := range tokenizerEventMap {
		RegisterEventType(k, ev)
	}
}

// Event codes
// TODO: get rid of these entirely?
const (
	EventTokenizerCreateAccessPolicy                 uclog.EventCode = 2610
	EventTokenizerCreateAccessPolicyDuration         uclog.EventCode = 2611
	EventTokenizerCreateAccessPolicyTemplate         uclog.EventCode = 4203
	EventTokenizerCreateAccessPolicyTemplateDuration uclog.EventCode = 4201
	EventTokenizerCreateGenerationPolicy             uclog.EventCode = 3995
	EventTokenizerCreateGenerationPolicyDuration     uclog.EventCode = 3997
	EventTokenizerCreateToken                        uclog.EventCode = 2570
	EventTokenizerCreateTokenDuration                uclog.EventCode = 2571
	EventTokenizerCreateTransformer                  uclog.EventCode = 2660
	EventTokenizerCreateTransformerDuration          uclog.EventCode = 2661
	EventTokenizerDeleteAccessPolicy                 uclog.EventCode = 2630
	EventTokenizerDeleteAccessPolicyDuration         uclog.EventCode = 2631
	EventTokenizerDeleteAccessPolicyTemplate         uclog.EventCode = 4189
	EventTokenizerDeleteAccessPolicyTemplateDuration uclog.EventCode = 4188
	EventTokenizerDeleteToken                        uclog.EventCode = 2580
	EventTokenizerDeleteTokenDuration                uclog.EventCode = 2581
	EventTokenizerDeleteTransformer                  uclog.EventCode = 2670
	EventTokenizerDeleteTransformerDuration          uclog.EventCode = 2671
	EventTokenizerExecuteAccessPolicy                uclog.EventCode = 3140
	EventTokenizerExecuteAccessPolicyDuration        uclog.EventCode = 3141
	EventTokenizerExecuteTransformer                 uclog.EventCode = 3130
	EventTokenizerExecuteTransformerDuration         uclog.EventCode = 3131
	EventTokenizerGetAccessPolicy                    uclog.EventCode = 2600
	EventTokenizerGetAccessPolicyDuration            uclog.EventCode = 2601
	EventTokenizerGetAccessPolicyTemplate            uclog.EventCode = 4208
	EventTokenizerGetAccessPolicyTemplateDuration    uclog.EventCode = 4190
	EventTokenizerGetGenerationPolicy                uclog.EventCode = 3996
	EventTokenizerGetGenerationPolicyDuration        uclog.EventCode = 3994
	EventTokenizerGetTransformer                     uclog.EventCode = 2650
	EventTokenizerGetTransformerDuration             uclog.EventCode = 2651
	EventTokenizerHandleGetDeployed                  uclog.EventCode = 2690
	EventTokenizerHandleGetDeployedDuration          uclog.EventCode = 2691
	EventTokenizerInitServiceHandlersFunc1           uclog.EventCode = 2680
	EventTokenizerInitServiceHandlersFunc1Duration   uclog.EventCode = 2681
	EventTokenizerInspectToken                       uclog.EventCode = 2810
	EventTokenizerInspectTokenDuration               uclog.EventCode = 2811
	EventTokenizerListAccessPolicies                 uclog.EventCode = 2590
	EventTokenizerListAccessPoliciesDuration         uclog.EventCode = 2591
	EventTokenizerListAccessPolicyTemplates          uclog.EventCode = 4187
	EventTokenizerListAccessPolicyTemplatesDuration  uclog.EventCode = 4202
	EventTokenizerListTransformers                   uclog.EventCode = 2640
	EventTokenizerListTransformersDuration           uclog.EventCode = 2641
	EventTokenizerLookupTokens                       uclog.EventCode = 2820
	EventTokenizerLookupTokensDuration               uclog.EventCode = 2821
	EventTokenizerResolveToken                       uclog.EventCode = 2830
	EventTokenizerResolveTokenDuration               uclog.EventCode = 2831
	EventTokenizerStartup                            uclog.EventCode = 1029
	EventTokenizerStatsHandlerFunc1                  uclog.EventCode = 3210
	EventTokenizerStatsHandlerFunc1Duration          uclog.EventCode = 3211
	EventTokenizerTestAccessPolicy                   uclog.EventCode = 2840
	EventTokenizerTestAccessPolicyDuration           uclog.EventCode = 2841
	EventTokenizerTestTransformer                    uclog.EventCode = 2850
	EventTokenizerTestTransformerDuration            uclog.EventCode = 2851
	EventTokenizerUpdateAccessPolicy                 uclog.EventCode = 2620
	EventTokenizerUpdateAccessPolicyDuration         uclog.EventCode = 2621
	EventTokenizerUpdateAccessPolicyTemplate         uclog.EventCode = 4207
	EventTokenizerUpdateAccessPolicyTemplateDuration uclog.EventCode = 4204
)

var tokenizerEventMap = map[string]uclog.LogEventTypeInfo{
	"idp.NewTokenizerClientHandler.func1.Count":        {Name: "Stats", NormalizedName: "Stats", Code: EventTokenizerStatsHandlerFunc1, Service: service.Tokenizer, Subcategory: "function", Ignore: true, URL: "", Category: uclog.EventCategoryCall},
	"idp.NewTokenizerClientHandler.func1.Duration":     {Name: "Stats", NormalizedName: "Stats", Code: EventTokenizerStatsHandlerFunc1Duration, Service: service.Tokenizer, Subcategory: "function", Ignore: true, URL: "", Category: uclog.EventCategoryDuration},
	"tokenizer.HandleGetDeployed.Count":                {Name: "Get Deployed Build", NormalizedName: "GetDeployedBuild", Code: EventTokenizerHandleGetDeployed, Service: service.Tokenizer, Subcategory: "function", Ignore: true, URL: "", Category: uclog.EventCategoryCall},
	"tokenizer.HandleGetDeployed.Duration":             {Name: "Get Deployed Build", NormalizedName: "GetDeployedBuild", Code: EventTokenizerHandleGetDeployedDuration, Service: service.Tokenizer, Subcategory: "function", Ignore: true, URL: "", Category: uclog.EventCategoryDuration},
	"tokenizer.Startup":                                {Name: "tokenizer Startup", NormalizedName: "tokenizerStartup", Code: EventTokenizerStartup, Service: service.Tokenizer, Subcategory: "event", URL: "", Category: uclog.EventCategorySystem},
	"tokenizer.createAccessPolicy-fm.Count":            {Name: "Create Access Policy", NormalizedName: "CreateAccessPolicy", Code: EventTokenizerCreateAccessPolicy, Service: service.Tokenizer, Subcategory: "function", URL: "/tokenizer/policies/access", Category: uclog.EventCategoryCall},
	"tokenizer.createAccessPolicy-fm.Duration":         {Name: "Create Access Policy", NormalizedName: "CreateAccessPolicy", Code: EventTokenizerCreateAccessPolicyDuration, Service: service.Tokenizer, Subcategory: "function", URL: "/tokenizer/policies/access", Category: uclog.EventCategoryDuration},
	"tokenizer.createAccessPolicyTemplate-fm.Count":    {Name: "Create Access Policy Template", NormalizedName: "CreateAccessPolicyTemplate", Code: EventTokenizerCreateAccessPolicyTemplate, Service: service.Tokenizer, Subcategory: "function", URL: "", Category: uclog.EventCategoryCall},
	"tokenizer.createAccessPolicyTemplate-fm.Duration": {Name: "Create Access Policy Template", NormalizedName: "CreateAccessPolicyTemplate", Code: EventTokenizerCreateAccessPolicyTemplateDuration, Service: service.Tokenizer, Subcategory: "function", URL: "", Category: uclog.EventCategoryDuration},
	"tokenizer.createGenerationPolicy-fm.Count":        {Name: "Create Generation Policy", NormalizedName: "CreateGenerationPolicy", Code: EventTokenizerCreateGenerationPolicy, Service: service.Tokenizer, Subcategory: "function", URL: "", Category: uclog.EventCategoryCall},
	"tokenizer.createGenerationPolicy-fm.Duration":     {Name: "Create Generation Policy", NormalizedName: "CreateGenerationPolicy", Code: EventTokenizerCreateGenerationPolicyDuration, Service: service.Tokenizer, Subcategory: "function", URL: "", Category: uclog.EventCategoryDuration},
	"tokenizer.createToken-fm.Count":                   {Name: "Create Token", NormalizedName: "CreateToken", Code: EventTokenizerCreateToken, Service: service.Tokenizer, Subcategory: "function", URL: "/tokenizer/tokens", Category: uclog.EventCategoryCall},
	"tokenizer.createToken-fm.Duration":                {Name: "Create Token", NormalizedName: "CreateToken", Code: EventTokenizerCreateTokenDuration, Service: service.Tokenizer, Subcategory: "function", URL: "/tokenizer/tokens", Category: uclog.EventCategoryDuration},
	"tokenizer.createTransformer-fm.Count":             {Name: "Create Transformer", NormalizedName: "CreateTransformer", Code: EventTokenizerCreateTransformer, Service: service.Tokenizer, Subcategory: "function", URL: "/tokenizer/policies/transformation", Category: uclog.EventCategoryCall},
	"tokenizer.createTransformer-fm.Duration":          {Name: "Create Transformer", NormalizedName: "CreateTransformer", Code: EventTokenizerCreateTransformerDuration, Service: service.Tokenizer, Subcategory: "function", URL: "/tokenizer/policies/transformation", Category: uclog.EventCategoryDuration},
	"tokenizer.deleteAccessPolicy-fm.Count":            {Name: "Delete Access Policy", NormalizedName: "DeleteAccessPolicy", Code: EventTokenizerDeleteAccessPolicy, Service: service.Tokenizer, Subcategory: "function", URL: "/tokenizer/policies/access/id", Category: uclog.EventCategoryCall},
	"tokenizer.deleteAccessPolicy-fm.Duration":         {Name: "Delete Access Policy", NormalizedName: "DeleteAccessPolicy", Code: EventTokenizerDeleteAccessPolicyDuration, Service: service.Tokenizer, Subcategory: "function", URL: "/tokenizer/policies/access/id", Category: uclog.EventCategoryDuration},
	"tokenizer.deleteAccessPolicyTemplate-fm.Count":    {Name: "Delete Access Policy Template", NormalizedName: "DeleteAccessPolicyTemplate", Code: EventTokenizerDeleteAccessPolicyTemplate, Service: service.Tokenizer, Subcategory: "function", URL: "", Category: uclog.EventCategoryCall},
	"tokenizer.deleteAccessPolicyTemplate-fm.Duration": {Name: "Delete Access Policy Template", NormalizedName: "DeleteAccessPolicyTemplate", Code: EventTokenizerDeleteAccessPolicyTemplateDuration, Service: service.Tokenizer, Subcategory: "function", URL: "", Category: uclog.EventCategoryDuration},
	"tokenizer.deleteToken-fm.Count":                   {Name: "Delete Token", NormalizedName: "DeleteToken", Code: EventTokenizerDeleteToken, Service: service.Tokenizer, Subcategory: "function", URL: "/tokenizer/tokens/id", Category: uclog.EventCategoryCall},
	"tokenizer.deleteToken-fm.Duration":                {Name: "Delete Token", NormalizedName: "DeleteToken", Code: EventTokenizerDeleteTokenDuration, Service: service.Tokenizer, Subcategory: "function", URL: "/tokenizer/tokens/id", Category: uclog.EventCategoryDuration},
	"tokenizer.deleteTransformer-fm.Count":             {Name: "Delete Transformer", NormalizedName: "DeleteTransformer", Code: EventTokenizerDeleteTransformer, Service: service.Tokenizer, Subcategory: "function", URL: "/tokenizer/policies/transformation/id", Category: uclog.EventCategoryCall},
	"tokenizer.deleteTransformer-fm.Duration":          {Name: "Delete Transformer", NormalizedName: "DeleteTransformer", Code: EventTokenizerDeleteTransformerDuration, Service: service.Tokenizer, Subcategory: "function", URL: "/tokenizer/policies/transformation/id", Category: uclog.EventCategoryDuration},
	"tokenizer.executeAccessPolicy-fm.Count":           {Name: "Execute Access Policy", NormalizedName: "ExecuteAccessPolicy", Code: EventTokenizerExecuteAccessPolicy, Service: service.Tokenizer, Subcategory: "function", URL: "", Category: uclog.EventCategoryCall},
	"tokenizer.executeAccessPolicy-fm.Duration":        {Name: "Execute Access Policy", NormalizedName: "ExecuteAccessPolicy", Code: EventTokenizerExecuteAccessPolicyDuration, Service: service.Tokenizer, Subcategory: "function", URL: "", Category: uclog.EventCategoryDuration},
	"tokenizer.executeTransformer-fm.Count":            {Name: "Execute Transformer", NormalizedName: "ExecuteTransformer", Code: EventTokenizerExecuteTransformer, Service: service.Tokenizer, Subcategory: "function", URL: "", Category: uclog.EventCategoryCall},
	"tokenizer.executeTransformer-fm.Duration":         {Name: "Execute Transformer", NormalizedName: "ExecuteTransformer", Code: EventTokenizerExecuteTransformerDuration, Service: service.Tokenizer, Subcategory: "function", URL: "", Category: uclog.EventCategoryDuration},
	"tokenizer.getAccessPolicy-fm.Count":               {Name: "Get Access Policy", NormalizedName: "GetAccessPolicy", Code: EventTokenizerGetAccessPolicy, Service: service.Tokenizer, Subcategory: "function", URL: "/tokenizer/policies/access/id", Category: uclog.EventCategoryCall},
	"tokenizer.getAccessPolicy-fm.Duration":            {Name: "Get Access Policy", NormalizedName: "GetAccessPolicy", Code: EventTokenizerGetAccessPolicyDuration, Service: service.Tokenizer, Subcategory: "function", URL: "/tokenizer/policies/access/id", Category: uclog.EventCategoryDuration},
	"tokenizer.getAccessPolicyTemplate-fm.Count":       {Name: "Get Access Policy Template", NormalizedName: "GetAccessPolicyTemplate", Code: EventTokenizerGetAccessPolicyTemplate, Service: service.Tokenizer, Subcategory: "function", URL: "", Category: uclog.EventCategoryCall},
	"tokenizer.getAccessPolicyTemplate-fm.Duration":    {Name: "Get Access Policy Template", NormalizedName: "GetAccessPolicyTemplate", Code: EventTokenizerGetAccessPolicyTemplateDuration, Service: service.Tokenizer, Subcategory: "function", URL: "", Category: uclog.EventCategoryDuration},
	"tokenizer.getGenerationPolicy-fm.Count":           {Name: "Get Generation Policy", NormalizedName: "GetGenerationPolicy", Code: EventTokenizerGetGenerationPolicy, Service: service.Tokenizer, Subcategory: "function", URL: "", Category: uclog.EventCategoryCall},
	"tokenizer.getGenerationPolicy-fm.Duration":        {Name: "Get Generation Policy", NormalizedName: "GetGenerationPolicy", Code: EventTokenizerGetGenerationPolicyDuration, Service: service.Tokenizer, Subcategory: "function", URL: "", Category: uclog.EventCategoryDuration},
	"tokenizer.getTransformer-fm.Count":                {Name: "Get Transformer", NormalizedName: "GetTransformer", Code: EventTokenizerGetTransformer, Service: service.Tokenizer, Subcategory: "function", URL: "/tokenizer/policies/transformation/id", Category: uclog.EventCategoryCall},
	"tokenizer.getTransformer-fm.Duration":             {Name: "Get Transformer", NormalizedName: "GetTransformer", Code: EventTokenizerGetTransformerDuration, Service: service.Tokenizer, Subcategory: "function", URL: "/tokenizer/policies/transformation/id", Category: uclog.EventCategoryDuration},
	"tokenizer.initServiceHandlers.func1.Count":        {Name: "Healthcheck", NormalizedName: "Healthcheck", Code: EventTokenizerInitServiceHandlersFunc1, Service: service.Tokenizer, Subcategory: "function", Ignore: true, URL: "", Category: uclog.EventCategoryCall},
	"tokenizer.initServiceHandlers.func1.Duration":     {Name: "Healthcheck", NormalizedName: "Healthcheck", Code: EventTokenizerInitServiceHandlersFunc1Duration, Service: service.Tokenizer, Subcategory: "function", Ignore: true, URL: "", Category: uclog.EventCategoryDuration},
	"tokenizer.inspectToken-fm.Count":                  {Name: "Inspect Token", NormalizedName: "InspectToken", Code: EventTokenizerInspectToken, Service: service.Tokenizer, Subcategory: "function", URL: "/tokenizer/tokens/actions/inspect", Category: uclog.EventCategoryCall},
	"tokenizer.inspectToken-fm.Duration":               {Name: "Inspect Token", NormalizedName: "InspectToken", Code: EventTokenizerInspectTokenDuration, Service: service.Tokenizer, Subcategory: "function", URL: "/tokenizer/tokens/actions/inspect", Category: uclog.EventCategoryDuration},
	"tokenizer.listAccessPolicies-fm.Count":            {Name: "List Access Policies", NormalizedName: "ListAccessPolicies", Code: EventTokenizerListAccessPolicies, Service: service.Tokenizer, Subcategory: "function", URL: "/tokenizer/policies/access", Category: uclog.EventCategoryCall},
	"tokenizer.listAccessPolicies-fm.Duration":         {Name: "List Access Policies", NormalizedName: "ListAccessPolicies", Code: EventTokenizerListAccessPoliciesDuration, Service: service.Tokenizer, Subcategory: "function", URL: "/tokenizer/policies/access", Category: uclog.EventCategoryDuration},
	"tokenizer.listAccessPolicyTemplates-fm.Count":     {Name: "List Access Policy Templates", NormalizedName: "ListAccessPolicyTemplates", Code: EventTokenizerListAccessPolicyTemplates, Service: service.Tokenizer, Subcategory: "function", URL: "", Category: uclog.EventCategoryCall},
	"tokenizer.listAccessPolicyTemplates-fm.Duration":  {Name: "List Access Policy Templates", NormalizedName: "ListAccessPolicyTemplates", Code: EventTokenizerListAccessPolicyTemplatesDuration, Service: service.Tokenizer, Subcategory: "function", URL: "", Category: uclog.EventCategoryDuration},
	"tokenizer.listTransformers-fm.Count":              {Name: "List Transformer", NormalizedName: "ListTransformer", Code: EventTokenizerListTransformers, Service: service.Tokenizer, Subcategory: "function", URL: "/tokenizer/policies/transformation", Category: uclog.EventCategoryCall},
	"tokenizer.listTransformers-fm.Duration":           {Name: "List Transformer", NormalizedName: "ListTransformer", Code: EventTokenizerListTransformersDuration, Service: service.Tokenizer, Subcategory: "function", URL: "/tokenizer/policies/transformation", Category: uclog.EventCategoryDuration},
	"tokenizer.lookupTokens-fm.Count":                  {Name: "Lookup Token", NormalizedName: "LookupToken", Code: EventTokenizerLookupTokens, Service: service.Tokenizer, Subcategory: "function", URL: "/tokenizer/tokens/actions/lookup", Category: uclog.EventCategoryCall},
	"tokenizer.lookupTokens-fm.Duration":               {Name: "Lookup Token", NormalizedName: "LookupToken", Code: EventTokenizerLookupTokensDuration, Service: service.Tokenizer, Subcategory: "function", URL: "/tokenizer/tokens/actions/lookup", Category: uclog.EventCategoryDuration},
	"tokenizer.resolveToken-fm.Count":                  {Name: "Resolve Token", NormalizedName: "ResolveToken", Code: EventTokenizerResolveToken, Service: service.Tokenizer, Subcategory: "function", URL: "/tokenizer/tokens/actions/resolve", Category: uclog.EventCategoryCall},
	"tokenizer.resolveToken-fm.Duration":               {Name: "Resolve Token", NormalizedName: "ResolveToken", Code: EventTokenizerResolveTokenDuration, Service: service.Tokenizer, Subcategory: "function", URL: "/tokenizer/tokens/actions/resolve", Category: uclog.EventCategoryDuration},
	"tokenizer.testAccessPolicy-fm.Count":              {Name: "Test Access Policy", NormalizedName: "TestAccessPolicy", Code: EventTokenizerTestAccessPolicy, Service: service.Tokenizer, Subcategory: "function", URL: "/tokenizer/policies/access/actions/test", Category: uclog.EventCategoryCall},
	"tokenizer.testAccessPolicy-fm.Duration":           {Name: "Test Access Policy", NormalizedName: "TestAccessPolicy", Code: EventTokenizerTestAccessPolicyDuration, Service: service.Tokenizer, Subcategory: "function", URL: "/tokenizer/policies/transformation/access/test", Category: uclog.EventCategoryDuration},
	"tokenizer.testTransformer-fm.Count":               {Name: "Test Transformer", NormalizedName: "TestTransformer", Code: EventTokenizerTestTransformer, Service: service.Tokenizer, Subcategory: "function", URL: "/tokenizer/policies/transformation/actions/test", Category: uclog.EventCategoryCall},
	"tokenizer.testTransformer-fm.Duration":            {Name: "Test Transformer", NormalizedName: "TestTransformer", Code: EventTokenizerTestTransformerDuration, Service: service.Tokenizer, Subcategory: "function", URL: "/tokenizer/policies/transformation/actions/test", Category: uclog.EventCategoryDuration},
	"tokenizer.updateAccessPolicy-fm.Count":            {Name: "Update Access Policy", NormalizedName: "UpdateAccessPolicy", Code: EventTokenizerUpdateAccessPolicy, Service: service.Tokenizer, Subcategory: "function", URL: "/tokenizer/policies/access/id", Category: uclog.EventCategoryCall},
	"tokenizer.updateAccessPolicy-fm.Duration":         {Name: "Update Access Policy", NormalizedName: "UpdateAccessPolicy", Code: EventTokenizerUpdateAccessPolicyDuration, Service: service.Tokenizer, Subcategory: "function", URL: "/tokenizer/policies/access/id", Category: uclog.EventCategoryDuration},
	"tokenizer.updateAccessPolicyTemplate-fm.Count":    {Name: "Update Access Policy Template", NormalizedName: "UpdateAccessPolicyTemplate", Code: EventTokenizerUpdateAccessPolicyTemplate, Service: service.Tokenizer, Subcategory: "function", URL: "", Category: uclog.EventCategoryCall},
	"tokenizer.updateAccessPolicyTemplate-fm.Duration": {Name: "Update Access Policy Template", NormalizedName: "UpdateAccessPolicyTemplate", Code: EventTokenizerUpdateAccessPolicyTemplateDuration, Service: service.Tokenizer, Subcategory: "function", URL: "", Category: uclog.EventCategoryDuration},
}
