// auto-generated by genevents
// your changes will be preserved inside both the EventCodes constant block
// and the EventMap block, but names are auto-generated and so won't necessarily
// be used if they are incorrect
package events

import (
	"userclouds.com/infra/namespace/service"
	"userclouds.com/infra/uclog"
)

func init() {
	for k, ev := range workerEventMap {
		RegisterEventType(k, ev)
	}
}

// Event codes
// TODO: get rid of these entirely?
const (
	EventWorkerGetRunningTasks                       uclog.EventCode = 7806
	EventWorkerGetRunningTasksDBGet                  uclog.EventCode = 7809
	EventWorkerGetRunningTasksDBGetDuration          uclog.EventCode = 7807
	EventWorkerGetRunningTasksDBSelect               uclog.EventCode = 7811
	EventWorkerGetRunningTasksDBSelectDuration       uclog.EventCode = 7804
	EventWorkerGetRunningTasksDBWrite                uclog.EventCode = 7810
	EventWorkerGetRunningTasksDBWriteDuration        uclog.EventCode = 7805
	EventWorkerGetRunningTasksDuration               uclog.EventCode = 7808
	EventWorkerHandleMessage                         uclog.EventCode = 5830
	EventWorkerHandleMessageDBGet                    uclog.EventCode = 5828
	EventWorkerHandleMessageDBGetDuration            uclog.EventCode = 5823
	EventWorkerHandleMessageDBSelect                 uclog.EventCode = 5827
	EventWorkerHandleMessageDBSelectDuration         uclog.EventCode = 5826
	EventWorkerHandleMessageDBWrite                  uclog.EventCode = 5829
	EventWorkerHandleMessageDBWriteDuration          uclog.EventCode = 5824
	EventWorkerHandleMessageDuration                 uclog.EventCode = 5825
	EventWorkerHandleMessageEndpoint                 uclog.EventCode = 7425
	EventWorkerHandleMessageEndpointDBGet            uclog.EventCode = 7423
	EventWorkerHandleMessageEndpointDBGetDuration    uclog.EventCode = 7426
	EventWorkerHandleMessageEndpointDBSelect         uclog.EventCode = 7421
	EventWorkerHandleMessageEndpointDBSelectDuration uclog.EventCode = 7428
	EventWorkerHandleMessageEndpointDBWrite          uclog.EventCode = 7427
	EventWorkerHandleMessageEndpointDBWriteDuration  uclog.EventCode = 7424
	EventWorkerHandleMessageEndpointDuration         uclog.EventCode = 7422
	EventWorkerHandleScheduled                       uclog.EventCode = 7354
	EventWorkerHandleScheduledDBGet                  uclog.EventCode = 7356
	EventWorkerHandleScheduledDBGetDuration          uclog.EventCode = 7357
	EventWorkerHandleScheduledDBSelect               uclog.EventCode = 7359
	EventWorkerHandleScheduledDBSelectDuration       uclog.EventCode = 7352
	EventWorkerHandleScheduledDBWrite                uclog.EventCode = 7353
	EventWorkerHandleScheduledDBWriteDuration        uclog.EventCode = 7358
	EventWorkerHandleScheduledDuration               uclog.EventCode = 7355
	EventWorkerStartup                               uclog.EventCode = 3882
)

var workerEventMap = map[string]uclog.LogEventTypeInfo{
	"worker.Startup":                                   {Name: "Worker Startup", NormalizedName: "WorkerStartup", Code: EventWorkerStartup, Service: service.Worker, Subcategory: "event", URL: "", Category: uclog.EventCategorySystem},
	"worker.getRunningTasks-fm.Count":                  {Name: "Get Running Tasks", NormalizedName: "GetRunningTasks", Code: EventWorkerGetRunningTasks, Service: service.Worker, Subcategory: "function", URL: "", Category: uclog.EventCategoryCall},
	"worker.getRunningTasks-fm.DBGetCount":             {Name: "Get Running Tasks", NormalizedName: "GetRunningTasks", Code: EventWorkerGetRunningTasksDBGet, Service: service.Worker, Subcategory: "db", URL: "", Category: uclog.EventCategoryCount},
	"worker.getRunningTasks-fm.DBGetDuration":          {Name: "Get Running Tasks", NormalizedName: "GetRunningTasks", Code: EventWorkerGetRunningTasksDBGetDuration, Service: service.Worker, Subcategory: "db", URL: "", Category: uclog.EventCategoryDuration},
	"worker.getRunningTasks-fm.DBSelectCount":          {Name: "Get Running Tasks", NormalizedName: "GetRunningTasks", Code: EventWorkerGetRunningTasksDBSelect, Service: service.Worker, Subcategory: "db", URL: "", Category: uclog.EventCategoryCount},
	"worker.getRunningTasks-fm.DBSelectDuration":       {Name: "Get Running Tasks", NormalizedName: "GetRunningTasks", Code: EventWorkerGetRunningTasksDBSelectDuration, Service: service.Worker, Subcategory: "db", URL: "", Category: uclog.EventCategoryDuration},
	"worker.getRunningTasks-fm.DBWriteCount":           {Name: "Get Running Tasks", NormalizedName: "GetRunningTasks", Code: EventWorkerGetRunningTasksDBWrite, Service: service.Worker, Subcategory: "db", URL: "", Category: uclog.EventCategoryCount},
	"worker.getRunningTasks-fm.DBWriteDuration":        {Name: "Get Running Tasks", NormalizedName: "GetRunningTasks", Code: EventWorkerGetRunningTasksDBWriteDuration, Service: service.Worker, Subcategory: "db", URL: "", Category: uclog.EventCategoryDuration},
	"worker.getRunningTasks-fm.Duration":               {Name: "Get Running Tasks", NormalizedName: "GetRunningTasks", Code: EventWorkerGetRunningTasksDuration, Service: service.Worker, Subcategory: "function", URL: "", Category: uclog.EventCategoryDuration},
	"worker.handleMessage-fm.Count":                    {Name: "Handle Message", NormalizedName: "HandleMessage", Code: EventWorkerHandleMessage, Service: service.Worker, Subcategory: "function", URL: "", Category: uclog.EventCategoryCall},
	"worker.handleMessage-fm.DBGetCount":               {Name: "Handle Message", NormalizedName: "HandleMessage", Code: EventWorkerHandleMessageDBGet, Service: service.Worker, Subcategory: "db", URL: "", Category: uclog.EventCategoryCount},
	"worker.handleMessage-fm.DBGetDuration":            {Name: "Handle Message", NormalizedName: "HandleMessage", Code: EventWorkerHandleMessageDBGetDuration, Service: service.Worker, Subcategory: "db", URL: "", Category: uclog.EventCategoryDuration},
	"worker.handleMessage-fm.DBSelectCount":            {Name: "Handle Message", NormalizedName: "HandleMessage", Code: EventWorkerHandleMessageDBSelect, Service: service.Worker, Subcategory: "db", URL: "", Category: uclog.EventCategoryCount},
	"worker.handleMessage-fm.DBSelectDuration":         {Name: "Handle Message", NormalizedName: "HandleMessage", Code: EventWorkerHandleMessageDBSelectDuration, Service: service.Worker, Subcategory: "db", URL: "", Category: uclog.EventCategoryDuration},
	"worker.handleMessage-fm.DBWriteCount":             {Name: "Handle Message", NormalizedName: "HandleMessage", Code: EventWorkerHandleMessageDBWrite, Service: service.Worker, Subcategory: "db", URL: "", Category: uclog.EventCategoryCount},
	"worker.handleMessage-fm.DBWriteDuration":          {Name: "Handle Message", NormalizedName: "HandleMessage", Code: EventWorkerHandleMessageDBWriteDuration, Service: service.Worker, Subcategory: "db", URL: "", Category: uclog.EventCategoryDuration},
	"worker.handleMessage-fm.Duration":                 {Name: "Handle Message", NormalizedName: "HandleMessage", Code: EventWorkerHandleMessageDuration, Service: service.Worker, Subcategory: "function", URL: "", Category: uclog.EventCategoryDuration},
	"worker.handleMessageEndpoint-fm.Count":            {Name: "Handle Message Endpoint", NormalizedName: "HandleMessageEndpoint", Code: EventWorkerHandleMessageEndpoint, Service: service.Worker, Subcategory: "function", URL: "", Category: uclog.EventCategoryCall},
	"worker.handleMessageEndpoint-fm.DBGetCount":       {Name: "Handle Message Endpoint", NormalizedName: "HandleMessageEndpoint", Code: EventWorkerHandleMessageEndpointDBGet, Service: service.Worker, Subcategory: "db", URL: "", Category: uclog.EventCategoryCount},
	"worker.handleMessageEndpoint-fm.DBGetDuration":    {Name: "Handle Message Endpoint", NormalizedName: "HandleMessageEndpoint", Code: EventWorkerHandleMessageEndpointDBGetDuration, Service: service.Worker, Subcategory: "db", URL: "", Category: uclog.EventCategoryDuration},
	"worker.handleMessageEndpoint-fm.DBSelectCount":    {Name: "Handle Message Endpoint", NormalizedName: "HandleMessageEndpoint", Code: EventWorkerHandleMessageEndpointDBSelect, Service: service.Worker, Subcategory: "db", URL: "", Category: uclog.EventCategoryCount},
	"worker.handleMessageEndpoint-fm.DBSelectDuration": {Name: "Handle Message Endpoint", NormalizedName: "HandleMessageEndpoint", Code: EventWorkerHandleMessageEndpointDBSelectDuration, Service: service.Worker, Subcategory: "db", URL: "", Category: uclog.EventCategoryDuration},
	"worker.handleMessageEndpoint-fm.DBWriteCount":     {Name: "Handle Message Endpoint", NormalizedName: "HandleMessageEndpoint", Code: EventWorkerHandleMessageEndpointDBWrite, Service: service.Worker, Subcategory: "db", URL: "", Category: uclog.EventCategoryCount},
	"worker.handleMessageEndpoint-fm.DBWriteDuration":  {Name: "Handle Message Endpoint", NormalizedName: "HandleMessageEndpoint", Code: EventWorkerHandleMessageEndpointDBWriteDuration, Service: service.Worker, Subcategory: "db", URL: "", Category: uclog.EventCategoryDuration},
	"worker.handleMessageEndpoint-fm.Duration":         {Name: "Handle Message Endpoint", NormalizedName: "HandleMessageEndpoint", Code: EventWorkerHandleMessageEndpointDuration, Service: service.Worker, Subcategory: "function", URL: "", Category: uclog.EventCategoryDuration},
	"worker.handleScheduled-fm.Count":                  {Name: "Handle Scheduled", NormalizedName: "HandleScheduled", Code: EventWorkerHandleScheduled, Service: service.Worker, Subcategory: "function", URL: "", Category: uclog.EventCategoryCall},
	"worker.handleScheduled-fm.DBGetCount":             {Name: "Handle Scheduled", NormalizedName: "HandleScheduled", Code: EventWorkerHandleScheduledDBGet, Service: service.Worker, Subcategory: "db", URL: "", Category: uclog.EventCategoryCount},
	"worker.handleScheduled-fm.DBGetDuration":          {Name: "Handle Scheduled", NormalizedName: "HandleScheduled", Code: EventWorkerHandleScheduledDBGetDuration, Service: service.Worker, Subcategory: "db", URL: "", Category: uclog.EventCategoryDuration},
	"worker.handleScheduled-fm.DBSelectCount":          {Name: "Handle Scheduled", NormalizedName: "HandleScheduled", Code: EventWorkerHandleScheduledDBSelect, Service: service.Worker, Subcategory: "db", URL: "", Category: uclog.EventCategoryCount},
	"worker.handleScheduled-fm.DBSelectDuration":       {Name: "Handle Scheduled", NormalizedName: "HandleScheduled", Code: EventWorkerHandleScheduledDBSelectDuration, Service: service.Worker, Subcategory: "db", URL: "", Category: uclog.EventCategoryDuration},
	"worker.handleScheduled-fm.DBWriteCount":           {Name: "Handle Scheduled", NormalizedName: "HandleScheduled", Code: EventWorkerHandleScheduledDBWrite, Service: service.Worker, Subcategory: "db", URL: "", Category: uclog.EventCategoryCount},
	"worker.handleScheduled-fm.DBWriteDuration":        {Name: "Handle Scheduled", NormalizedName: "HandleScheduled", Code: EventWorkerHandleScheduledDBWriteDuration, Service: service.Worker, Subcategory: "db", URL: "", Category: uclog.EventCategoryDuration},
	"worker.handleScheduled-fm.Duration":               {Name: "Handle Scheduled", NormalizedName: "HandleScheduled", Code: EventWorkerHandleScheduledDuration, Service: service.Worker, Subcategory: "function", URL: "", Category: uclog.EventCategoryDuration},
}
