// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package ucjsontest

import (
	json "encoding/json"

	easyjson "github.com/userclouds/easyjson"
	jlexer "github.com/userclouds/easyjson/jlexer"
	jwriter "github.com/userclouds/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

// easyjsonF6ec53d6DecodeUsercloudsComInfraUcjsonUcjsontest implements json.Unmarshaler interface
func easyjsonF6ec53d6DecodeUsercloudsComInfraUcjsonUcjsontest(in *jlexer.Lexer, out *EasyJSONTest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

// easyjsonF6ec53d6EncodeUsercloudsComInfraUcjsonUcjsontest implements json.Marshaler interface
func easyjsonF6ec53d6EncodeUsercloudsComInfraUcjsonUcjsontest(out *jwriter.Writer, in EasyJSONTest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v EasyJSONTest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonF6ec53d6EncodeUsercloudsComInfraUcjsonUcjsontest(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v EasyJSONTest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonF6ec53d6EncodeUsercloudsComInfraUcjsonUcjsontest(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *EasyJSONTest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonF6ec53d6DecodeUsercloudsComInfraUcjsonUcjsontest(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *EasyJSONTest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonF6ec53d6DecodeUsercloudsComInfraUcjsonUcjsontest(l, v)
}
