# Generated by Django 5.0.6 on 2024-06-12 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='sensitive',
            field=models.BooleanField(default=False),
        ),
    ]
