const pageParameterNames = {
  ActionButtonBorderColor: 'actionButtonBorderColor',
  ActionButtonFillColor: 'actionButtonFillColor',
  ActionButtonTextColor: 'actionButtonTextColor',
  ActionSubmitButtonText: 'actionSubmitButtonText',
  AllowCreation: 'allowCreation',
  AuthenticationMethods: 'authenticationMethods',
  CreateAccountText: 'createAccountText',
  CreateUserDisabledText: 'createUserDisabledText',
  CreateUserFailStatusText: 'createUserFailStatusText',
  CreateUserStartStatusText: 'createUserStartStatusText',
  CustomCreateUserPagePostFieldsetHTMLCSS:
    'customCreateUserPagePostFieldsetHTMLCSS',
  CustomCreateUserPagePreFieldsetHTMLCSS:
    'customCreateUserPagePreFieldsetHTMLCSS',
  CustomCreateUserPagePostFormHTMLCSS: 'customCreateUserPagePostFormHTMLCSS',
  CustomCreateUserPagePreFormHTMLCSS: 'customCreateUserPagePreFormHTMLCSS',
  CustomCreateUserPagePreMainHTMLCSS: 'customCreateUserPagePreMainHTMLCSS',
  CustomLoginPagePostFieldsetHTMLCSS: 'customLoginPagePostFieldsetHTMLCSS',
  CustomLoginPagePreFieldsetHTMLCSS: 'customLoginPagePreFieldsetHTMLCSS',
  CustomLoginPagePostFormHTMLCSS: 'customLoginPagePostFormHTMLCSS',
  CustomLoginPagePreFormHTMLCSS: 'customLoginPagePreFormHTMLCSS',
  CustomLoginPagePreMainHTMLCSS: 'customLoginPagePreMainHTMLCSS',
  DisabledAuthenticationMethods: 'disabledAuthenticationMethods',
  DisabledMFAMethods: 'disabledMFAMethods',
  EmailLabel: 'emailLabel',
  EmailExistsCreateAccountText: 'emailExistsCreateAccountText',
  EmailExistsLoginText: 'emailExistsLoginText',
  EnabledAuthenticationMethods: 'enabledAuthenticationMethods',
  EnabledMFAMethods: 'enabledMFAMethods',
  FooterHTML: 'footerHTML',
  ForgotPasswordText: 'forgotPasswordText',
  HeadingText: 'headingText',
  LoginFailStatusText: 'loginFailStatusText',
  LoginStartStatusText: 'loginStartStatusText',
  LoginSuccessStatusText: 'loginSuccessStatusText',
  LogoImageFile: 'logoImageFile',
  MissingOTPCodeText: 'missingOTPCodeText',
  MFACodeLabel: 'mfaCodeLabel',
  MFAMethods: 'mfaMethods',
  MFARequired: 'mfaRequired',
  NewPasswordLabel: 'newPasswordLabel',
  OIDCAuthenticationSettings: 'oidcAuthenticationSettings',
  OtpCodeLabel: 'otpCodeLabel',
  PageBackgroundColor: 'pageBackgroundColor',
  PageOrderSocialFirst: 'pageOrderSocialFirst',
  PageTextColor: 'pageTextColor',
  PasswordLabel: 'passwordLabel',
  PasswordlessLoginText: 'passwordlessLoginText',
  PasswordlessSendEmailStartStatusText: 'passwordlessSendEmailStartStatusText',
  PasswordlessSendEmailSuccessStatusText:
    'passwordlessSendEmailSuccessStatusText',
  PasswordResetEnabled: 'passwordResetEnabled',
  RequireName: 'requireName',
  ResetPasswordFailStatusText: 'resetPasswordFailStatusText',
  ResetPasswordStartStatusText: 'resetPasswordStartStatusText',
  ResetPasswordSuccessStatusText: 'resetPasswordSuccessStatusText',
  SocialRedirectStatusText: 'socialRedirectStatusText',
  SubheadingText: 'subheadingText',
  UserNameLabel: 'userNameLabel',
};

export default pageParameterNames;
