// NOTE: automatically generated file -- DO NOT EDIT

package storage

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"time"

	"github.com/gofrs/uuid"

	"userclouds.com/infra/cache"
	"userclouds.com/infra/pagination"
	"userclouds.com/infra/ucdb"
	"userclouds.com/infra/ucerr"
	"userclouds.com/infra/uclog"
)

// IsAccessorSoftDeleted returns true if the id is associated with a soft-deleted row but no undeleted rows
func (s *Storage) IsAccessorSoftDeleted(ctx context.Context, id uuid.UUID) (bool, error) {
	var err error
	conflict := cache.GenerateTombstoneSentinel()

	if s.cm != nil {
		var cachedObj *Accessor
		cachedObj, conflict, _, err = cache.GetItemFromCacheWithModifiedKey[Accessor](ctx, *s.cm, s.cm.N.GetKeyNameWithID(AccessorKeyID, id), s.cm.N.GetKeyNameWithID(IsModifiedKeyID, id), false)
		if err != nil {
			if errors.Is(err, context.Canceled) {
				uclog.Warningf(ctx, "[IsAccessorSoftDeleted] error reading from cache: %v", err)
			} else {
				uclog.Errorf(ctx, "[IsAccessorSoftDeleted] error reading from cache: %v", err)
			}
		} else if cachedObj != nil {
			return false, nil
		}
	}
	const q = "/* lint-sql-ok */ SELECT deleted FROM accessors WHERE id=$1 ORDER By deleted LIMIT 1;"

	var deleted time.Time
	if err := s.db.GetContextWithDirty(ctx, "IsAccessorSoftDeleted", &deleted, q, cache.IsTombstoneSentinel(string(conflict)), id); err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return false, nil
		}

		return false, ucerr.Wrap(err)
	}

	return !deleted.IsZero(), nil
}

// GetLatestAccessor looks up the latest version of Accessor by ID
func (s *Storage) GetLatestAccessor(ctx context.Context, id uuid.UUID) (*Accessor, error) {
	var err error
	sentinel := cache.NoLockSentinel
	conflict := cache.GenerateTombstoneSentinel()
	if s.cm != nil {
		var cachedObj *Accessor
		cachedObj, conflict, sentinel, err = cache.GetItemFromCacheWithModifiedKey[Accessor](ctx, *s.cm, s.cm.N.GetKeyNameWithID(AccessorKeyID, id), s.cm.N.GetKeyNameWithID(IsModifiedKeyID, id), true)
		if err != nil {
			if errors.Is(err, context.Canceled) {
				uclog.Warningf(ctx, "[GetLatestAccessor] error reading from local cache: %v", err)
			} else {
				uclog.Errorf(ctx, "[GetLatestAccessor] error reading from local cache: %v", err)
			}
		} else if cachedObj != nil {
			return cachedObj, nil
		}
	}
	const q = "SELECT id, updated, deleted, is_system, name, description, version, data_life_cycle_state, access_policy_id, column_ids, transformer_ids, token_access_policy_ids, selector_config, purpose_ids, is_audit_logged, is_autogenerated, are_column_access_policies_overridden, search_column_id, use_search_index, created FROM accessors WHERE id=$1 AND deleted='0001-01-01 00:00:00' ORDER BY version DESC LIMIT 1;"
	var obj Accessor
	if err := s.db.GetContextWithDirty(ctx, "GetLatestAccessor", &obj, q, cache.IsTombstoneSentinel(string(conflict)), id); err != nil {

		if errors.Is(err, sql.ErrNoRows) {
			return nil, ucerr.Friendlyf(err, "Accessor %v not found", id)
		}
		return nil, ucerr.Wrap(err)
	}
	if s.cm != nil {
		cache.SaveItemToCache(ctx, *s.cm, obj, sentinel, false, nil)
	}
	return &obj, nil
}

// ListAccessorsPaginated loads a paginated list of Accessors for the specified paginator settings
func (s *Storage) ListAccessorsPaginated(ctx context.Context, p pagination.Paginator) ([]Accessor, *pagination.ResponseFields, error) {
	return s.listInnerAccessorsPaginated(ctx, p, false)
}

// listInnerAccessorsPaginated loads a paginated list of Accessors for the specified paginator settings
func (s *Storage) listInnerAccessorsPaginated(ctx context.Context, p pagination.Paginator, forceDBRead bool) ([]Accessor, *pagination.ResponseFields, error) {
	var lkey, ckey cache.Key
	sentinel := cache.NoLockSentinel
	conflict := cache.GenerateTombstoneSentinel()
	cachable := p.IsCachable() && p.GetCursor() == ""
	if s.cm != nil { // We need the check the cache even if the result is not cachable to see if a stale read is allowed
		lkey = s.cm.N.GetKeyNameStatic(AccessorCollectionKeyID)
		ckey = lkey
		var err error
		var v *[]Accessor
		v, conflict, sentinel, _, err = cache.GetItemsArrayFromCache[Accessor](ctx, *s.cm, ckey, cachable)
		if err != nil {
			return nil, nil, ucerr.Wrap(err)
		}
		if cachable && v != nil {
			v, respFields := pagination.ProcessResults(*v, p.GetCursor(), p.GetLimit(), p.IsForward(), p.GetSortKey())
			return v, &respFields, nil
		}
	}
	queryFields, err := p.GetQueryFields()
	if err != nil {
		return nil, nil, ucerr.Wrap(err)
	}

	// the inner query requires an alias for postgres, so we always call it tmp
	// the outer query is just to reverse the order of the results in the case of paging backwards with forward sort
	q := fmt.Sprintf("SELECT id, updated, deleted, is_system, name, description, version, data_life_cycle_state, access_policy_id, column_ids, transformer_ids, token_access_policy_ids, selector_config, purpose_ids, is_audit_logged, is_autogenerated, are_column_access_policies_overridden, search_column_id, use_search_index, created FROM (SELECT id, updated, deleted, is_system, name, description, version, data_life_cycle_state, access_policy_id, column_ids, transformer_ids, token_access_policy_ids, selector_config, purpose_ids, is_audit_logged, is_autogenerated, are_column_access_policies_overridden, search_column_id, use_search_index, created FROM accessors WHERE deleted='0001-01-01 00:00:00' %s ORDER BY %s LIMIT %d) tmp ORDER BY %s;", p.GetWhereClause(), p.GetInnerOrderByClause(), p.GetLimit()+1, p.GetOuterOrderByClause())

	var objsDB []Accessor
	if err := s.db.SelectContextWithDirty(ctx, "ListAccessorsPaginated", &objsDB, q, cache.IsTombstoneSentinel(string(conflict)), queryFields...); err != nil {
		return nil, nil, ucerr.Wrap(err)
	}
	objs, respFields := pagination.ProcessResults(objsDB, p.GetCursor(), p.GetLimit(), p.IsForward(), p.GetSortKey())
	if respFields.HasNext {
		if err := p.ValidateCursor(respFields.Next); err != nil {
			return nil, nil, ucerr.Wrap(err)
		}
	}

	if respFields.HasPrev {
		if err := p.ValidateCursor(respFields.Prev); err != nil {
			return nil, nil, ucerr.Wrap(err)
		}
	}
	if s.cm != nil && cachable && !respFields.HasNext && !respFields.HasPrev { /* only cache single page collections */
		cache.SaveItemsToCollection(ctx, *s.cm, Accessor{}, objsDB, lkey, ckey, sentinel, true)
	}

	return objs, &respFields, nil
}

// ListAccessorsNonPaginated loads a Accessor up to a limit of 10 pages
func (s *Storage) ListAccessorsNonPaginated(ctx context.Context) ([]Accessor, error) {
	sentinel := cache.NoLockSentinel
	if s.cm != nil {
		var err error
		var v *[]Accessor
		v, _, sentinel, _, err = cache.GetItemsArrayFromCache[Accessor](ctx, *s.cm, s.cm.N.GetKeyNameStatic(AccessorCollectionKeyID), true)
		if err != nil {
			return nil, ucerr.Wrap(err)
		}
		if v != nil {
			return *v, nil
		}
	}
	pager, err := NewAccessorPaginatorFromOptions(pagination.Limit(pagination.MaxLimit))
	if err != nil {
		return nil, ucerr.Wrap(err)
	}

	objs := make([]Accessor, 0)

	pageCount := 0
	for {
		objRead, respFields, err := s.ListAccessorsPaginated(ctx, *pager)
		if err != nil {
			return nil, ucerr.Wrap(err)
		}
		objs = append(objs, objRead...)
		pageCount++
		if s.cm != nil {
			// Save individual items to cache under their own primary keys (optional)
			cache.SaveItemsFromCollectionToCache(ctx, *s.cm, objRead, sentinel)
		}
		if !pager.AdvanceCursor(*respFields) {
			break
		}
		if pageCount >= 10 {
			return nil, ucerr.Errorf("ListAccessorsNonPaginated exceeded max page count of 10")
		}
	}
	if s.cm != nil {
		ckey := s.cm.N.GetKeyNameStatic(AccessorCollectionKeyID)
		cache.SaveItemsToCollection(ctx, *s.cm, Accessor{}, objs, ckey, ckey, sentinel, true)
	}
	return objs, nil
}

// SaveAccessor saves a Accessor
func (s *Storage) SaveAccessor(ctx context.Context, obj *Accessor) error {
	if err := obj.Validate(); err != nil {
		return ucerr.Wrap(err)
	}
	return ucerr.Wrap(cache.CreateItemServer(ctx, s.cm, obj, AccessorKeyID, nil, func(i *Accessor) error {
		return ucerr.Wrap(s.saveInnerAccessor(ctx, obj))
	}))
}

// SaveAccessor saves a Accessor
func (s *Storage) saveInnerAccessor(ctx context.Context, obj *Accessor) error {
	const q = "INSERT INTO accessors (id, updated, deleted, is_system, name, description, version, data_life_cycle_state, access_policy_id, column_ids, transformer_ids, token_access_policy_ids, selector_config, purpose_ids, is_audit_logged, is_autogenerated, are_column_access_policies_overridden, search_column_id, use_search_index) VALUES ($1, CLOCK_TIMESTAMP(), $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18) ON CONFLICT (id, version, deleted) DO UPDATE SET updated = CLOCK_TIMESTAMP(), deleted = $2, is_system = $3, name = $4, description = $5, version = $6, data_life_cycle_state = $7, access_policy_id = $8, column_ids = $9, transformer_ids = $10, token_access_policy_ids = $11, selector_config = $12, purpose_ids = $13, is_audit_logged = $14, is_autogenerated = $15, are_column_access_policies_overridden = $16, search_column_id = $17, use_search_index = $18 WHERE (accessors.id = $1) RETURNING created, updated; /* allow-multiple-target-use no-match-cols-vals */"
	if err := s.db.GetContext(ctx, "SaveAccessor", obj, q, obj.ID, obj.Deleted, obj.IsSystem, obj.Name, obj.Description, obj.Version, obj.DataLifeCycleState, obj.AccessPolicyID, obj.ColumnIDs, obj.TransformerIDs, obj.TokenAccessPolicyIDs, obj.SelectorConfig, obj.PurposeIDs, obj.IsAuditLogged, obj.IsAutogenerated, obj.AreColumnAccessPoliciesOverridden, obj.SearchColumnID, obj.UseSearchIndex); err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return ucerr.Friendlyf(err, "Accessor %v not found", obj.ID)
		}
		return ucerr.Wrap(err)
	}
	return nil
}

// PriorVersionSaveAccessor saves an older version of Accessor
func (s *Storage) PriorVersionSaveAccessor(ctx context.Context, obj *Accessor) error {
	if err := obj.Validate(); err != nil {
		return ucerr.Wrap(err)
	}
	return ucerr.Wrap(s.saveInnerAccessor(ctx, obj))
}

// DeleteAccessorByVersion soft-deletes a Accessor which is currently alive
// Note that this will fail on an already-deleted object (since we don't want to re-delete
// tombstoned objects and corrupt the deletion timestamp)
func (s Storage) DeleteAccessorByVersion(ctx context.Context, objID uuid.UUID, version int) error {
	if s.cm != nil {
		obj, _, _, err := cache.GetItemFromCache[Accessor](ctx, *s.cm, s.cm.N.GetKeyNameWithID(AccessorKeyID, objID), false)
		if err != nil {
			return ucerr.Wrap(err)
		}

		objBase := Accessor{SystemAttributeBaseModel: ucdb.NewSystemAttributeBaseWithID(objID)}
		if obj == nil {
			obj = &objBase
		}
		sentinel, err := cache.TakeItemLock(ctx, cache.Delete, *s.cm, *obj)
		if err != nil {
			uclog.Warningf(ctx, "Error taking lock for delete: %v", err)
			return ucerr.Wrap(err)
		}
		// This generates an extra invalidation for items that don't exist
		defer cache.DeleteItemFromCache[Accessor](ctx, *s.cm, *obj, sentinel)
	}
	const q = "UPDATE accessors SET deleted=CLOCK_TIMESTAMP() WHERE id=$1 AND version=$2 AND deleted='0001-01-01 00:00:00' RETURNING deleted;"
	_, err := s.db.ExecContext(ctx, "DeleteAccessorByVersion", q, objID, version)
	return ucerr.Wrap(err)
}

// DeleteAllAccessorVersions soft-deletes all versions of a Accessor
func (s Storage) DeleteAllAccessorVersions(ctx context.Context, objID uuid.UUID) error {
	if s.cm != nil {
		obj, _, _, err := cache.GetItemFromCache[Accessor](ctx, *s.cm, s.cm.N.GetKeyNameWithID(AccessorKeyID, objID), false)
		if err != nil {
			return ucerr.Wrap(err)
		}

		objBase := Accessor{SystemAttributeBaseModel: ucdb.NewSystemAttributeBaseWithID(objID)}
		if obj == nil {
			obj = &objBase
		}
		sentinel, err := cache.TakeItemLock(ctx, cache.Delete, *s.cm, *obj)
		if err != nil {
			uclog.Warningf(ctx, "Error taking lock for delete: %v", err)
			return ucerr.Wrap(err)
		}
		// This generates an extra invalidation for items that don't exist
		defer cache.DeleteItemFromCache[Accessor](ctx, *s.cm, *obj, sentinel)
	}
	const q = "UPDATE accessors SET deleted=CLOCK_TIMESTAMP() WHERE id=$1 AND deleted='0001-01-01 00:00:00' RETURNING deleted;"
	_, err := s.db.ExecContext(ctx, "DeleteAllAccessorVersions", q, objID)
	return ucerr.Wrap(err)
}

// FlushCacheForAccessor flushes cache for Accessor. It may flush a larger scope then
func (s *Storage) FlushCacheForAccessor(ctx context.Context, objID uuid.UUID) error {
	if s.cm == nil {
		return nil
	}
	return ucerr.Wrap(s.cm.Flush(ctx, "Accessor"))
}
